const caution = 'This page does not quote a live price, a dividend amount, or a target. Those figures belong in the company’s own notices, your broker, and — for a fund — the manager’s statement and MUFAP’s published NAV. PSX Tracker is not a broker and does not place orders.';

function share(symbol, name, sections) {
  return {
    kind: 'share',
    symbol,
    title: `${name} (${symbol})`,
    seoTitle: `${symbol} share research notes`,
    description: `What ${name} does, what investors usually read in its filings, and how to record ${symbol} in a portfolio. No live price.`,
    eyebrow: 'Listed company',
    h1: `${name} (${symbol})`,
    intro: `${name} is listed on the Pakistan Stock Exchange under ${symbol}. This note says what the business is and which documents to read. It is not a recommendation and it does not publish a price.`,
    sections,
    faqs: [
      [`Does this page show the live ${symbol} price?`, 'No. Publishing a scraped quote would copy someone else’s market data. Open your broker for the price you can trade, or the app after you sign in, for the research view.'],
      [`Is ${symbol} a buy?`, 'No. This site does not rank or recommend shares. Read the latest accounts and decide for yourself.'],
      [`How should I record ${symbol} I already own?`, 'Enter each fill with its date, quantity, price, and fees, then reconcile the quantity to your broker or CDC statement. Dividends go in as dividends, not as new deposits.'],
    ],
  };
}

export const editorialPages = {
  '/markets': {
    kind: 'hub',
    title: 'PSX companies and mutual funds',
    seoTitle: 'PSX companies and mutual funds',
    description: 'Research notes on listed companies and open-end funds, without republished live prices.',
    eyebrow: 'Research notes',
    h1: 'Companies and funds, without a republished price',
    intro: 'These pages describe a handful of widely followed PSX shares and open-end funds: what they do, which filings matter, and how a personal ledger should treat them. They do not copy the live tape or MUFAP’s NAV file.',
    sections: [
      ['Why there is no price on the page',
        'A share price is the exchange’s and your broker’s number. A fund NAV is the manager’s number, published through channels such as MUFAP. Copying those feeds onto a public page raises a data-use question this site does not need to settle, and a stale copied price is worse than none. Use the broker to trade. Use the app, once you are signed in, for charts and a ledger.',
        'What a public page can honestly do is teach the paperwork: which report to open, which events change your quantity, and which events are only cash.'],
      ['Shares',
        { links: [
          { href: '/markets/shares/ogdc', label: 'Oil & Gas Development Company (OGDC)' },
          { href: '/markets/shares/ppl', label: 'Pakistan Petroleum (PPL)' },
          { href: '/markets/shares/pol', label: 'Pakistan Oilfields (POL)' },
          { href: '/markets/shares/hubc', label: 'Hub Power (HUBC)' },
          { href: '/markets/shares/luck', label: 'Lucky Cement (LUCK)' },
          { href: '/markets/shares/ffc', label: 'Fauji Fertilizer (FFC)' },
          { href: '/markets/shares/mcb', label: 'MCB Bank (MCB)' },
          { href: '/markets/shares/mebl', label: 'Meezan Bank (MEBL)' },
          { href: '/markets/shares/sys', label: 'Systems Limited (SYS)' },
        ] }],
      ['Open-end funds',
        { links: [
          { href: '/markets/funds/meezan-islamic-fund', label: 'Meezan Islamic Fund' },
          { href: '/markets/funds/al-meezan-mutual-fund', label: 'Al Meezan Mutual Fund' },
          { href: '/markets/funds/ubl-stock-advantage-fund', label: 'UBL Stock Advantage Fund' },
        ] },
        'Fund pages talk about units and statements. They do not reprint today’s NAV.'],
      ['Tools that use your own numbers',
        'Calculators for a disposal, FIFO versus average cost, a dividend yield, and a trade’s charges sit under Tools. You type every input. Nothing is fetched from the market.',
        { links: [{ href: '/tools', label: 'Open the calculators' }] }],
    ],
    faqs: [
      ['Are these all the PSX symbols?', 'No. A page for every ticker, generated from one template, would be a pile of thin duplicates. These notes are ones people ask about often, written as themselves.'],
      ['Can I trade from here?', 'No. Orders go through a licensed broker. This site does not open accounts and does not send orders.'],
      ['Where do I track a holding?', 'In the app, after you sign in, with the contract note beside you. The guides explain FIFO, dividends, and reconciliation.'],
    ],
  },

  '/markets/shares/ogdc': share('OGDC', 'Oil and Gas Development Company', [
    ['The business',
      'Oil and Gas Development Company is a listed exploration and production company. It searches for and produces oil and gas in Pakistan. Revenue follows the volumes it produces and the prices and tariffs that apply to those volumes, not the daily mood of an unrelated sector.',
      'Investors usually read it next to other exploration names such as PPL and POL, and then stop the comparison there. A gas utility, a refiner, and an explorer do not share a cost structure. The annual report’s description of fields and production is the primary source, not a forum summary.',
      caution],
    ['What the filings are for',
      'Production, reserves, and the receivable from the gas chain are the recurring themes in the company’s own discussion. Receivables matter because a sale that has not been collected is not cash. The cash-flow statement is the check on the profit line.',
      'Dividends, when declared, are a company notice with a rate, a book closure, and a face value. Record the cash when it arrives, and record withholding separately. Do not invent a yield on this page and then trade it.'],
    ['In a personal ledger',
      'Each buy and sell is a lot at the contract-note price plus fees. A bonus or a rights issue is its own event. Transferring OGDC shares between two portfolios you own is not a sale and should keep the original cost.',
      'Reconcile the quantity to CDC or the broker after any book closure. The tracker’s job is to remember the lots. The exchange’s job is the tape. They are not the same job.'],
  ]),

  '/markets/shares/ppl': share('PPL', 'Pakistan Petroleum', [
    ['The business',
      'Pakistan Petroleum is a listed exploration and production company. Like OGDC, it lives or dies by the hydrocarbons it produces and by how and when it gets paid. It is not a retail fuel brand and it is not a power plant.',
      'Read the latest annual report for the fields it talks about and for the split between oil and gas. That mix changes how sensitive the year is to a particular price. A paragraph from memory will be out of date. The report will not.',
      caution],
    ['What to compare',
      'Compare PPL with other explorers on production, reserves, and cash collection, using each company’s own figures. Comparing an explorer’s P/E with a bank’s P/E is not research. The P/E guide explains that trap in general. The bank guide explains why banks are a different animal.',
      'Any Shariah screening status belongs to the published methodology and the dated list, not to this paragraph. The screening guide tells you how to read those documents.'],
    ['In a personal ledger',
      'Keep PPL lots separate from OGDC lots even if you think of them as one theme. They are different issuers, different notices, and different dividends. A combined “oil” line in a spreadsheet hides which contract note is missing.',
      'Fees sit in the cost. A dividend sits in income. A deposit of fresh savings sits in neither. That separation is the whole bookkeeping point of holding a producer through a noisy year.'],
  ]),

  '/markets/shares/pol': share('POL', 'Pakistan Oilfields', [
    ['The business',
      'Pakistan Oilfields is a listed exploration and production company in the Attock group. The group connection is a reason to read the related-party note, not a reason to skip the company’s own accounts. The listed entity’s results are the ones you own.',
      'Production and the price realization on that production are the operating story. The notes will say more than a share-price chart about whether a particular field’s decline or a new development is the thing that mattered last year.',
      caution],
    ['Reading the group without mixing the cash',
      'A group can contain a refinery, a marketer, and an explorer. Only POL’s shares are POL’s shares. Dividends you receive are the ones POL’s notice names. A dividend announced by a different group company is not yours unless you hold that other company too.',
      'Related-party balances can be material. Read them. They tell you whether cash and profits move between group entities on terms you understand.'],
    ['In a personal ledger',
      'Record the symbol POL, not the group’s name, on every trade. Imports that map a long legal name incorrectly will create a second holding and a quantity that never matches CDC.',
      'After the annual accounts, you do not change the cost basis. The accounts change your opinion. The cost basis changes only when you buy, sell, or record a corporate action.'],
  ]),

  '/markets/shares/hubc': share('HUBC', 'The Hub Power Company', [
    ['The business',
      'Hub Power is a listed power producer. Its story is plants, the contracts and tariffs that pay them, and the fuel and financing attached to them, plus interests in other power projects the report describes. It is not an exploration company, even though both can be sensitive to energy policy.',
      'Income investors often study Hub Power because power producers have historically been discussed as dividend payers. “Historically” is not “next quarter.” The dividend you can plan around is the one in the latest notice, with its book closure, and only if you held the shares for that closure.',
      caution],
    ['What the accounts are really about',
      'Look for capacity payments versus energy payments if the report splits them, for receivables from the power purchaser, and for debt taken on to build plants. A profit that sits in receivables has not arrived as cash. Circular-debt discussions in the director’s report are there for that reason.',
      'Project companies and associates may sit beside the parent. The consolidated total and the standalone total answer different questions. Know which one you are reading when you quote a profit.'],
    ['In a personal ledger',
      'Treat each dividend as its own cash event with withholding recorded beside it. Treat a bonus, if one is declared, as a share event that changes quantity and cost per share, not as cash.',
      'Do not set a tracker cost equal to a “fair value” you estimated. Cost is what you paid. Value is an opinion you can keep in a note. Mixing them makes the unrealized figure meaningless.'],
  ]),

  '/markets/shares/luck': share('LUCK', 'Lucky Cement', [
    ['The business',
      'Lucky Cement is a listed cement manufacturer. It quarries, produces clinker and cement, and sells into construction demand. The group also has interests beyond cement, including operations the annual report describes in other industries and in other countries. Those interests are why the segment note matters more here than a single “bags sold” headline.',
      'Cement is heavy and local. A plant’s location, its fuel, and the price of a bag decide the margin. Monthly dispatch headlines, when published, are volume only. Volume without price and cost is not a profit.',
      caution],
    ['How to read a cement year',
      'Use the cement guide’s checklist: dispatches if you have a primary figure, margins, debt, and the project pipeline, then a valuation against other cement producers. Lucky’s non-cement segments need their own sentence so you do not credit the kiln for a profit earned elsewhere.',
      'Expansion projects absorb cash before they produce bags. The project note has the budget and the funding. A thesis that needs a line to start in a specific quarter should survive the line being late.'],
    ['In a personal ledger',
      'LUCK shares are ordinary lots. A split or a bonus changes the count and, if you adjust only the price chart and not the ledger, your cost per share will be wrong. Record the corporate action from the notice.',
      'Keep cement names separate in the book. A blended “cement” quantity cannot be reconciled to any one CDC line.'],
  ]),

  '/markets/shares/ffc': share('FFC', 'Fauji Fertilizer Company', [
    ['The business',
      'Fauji Fertilizer Company is a listed fertilizer producer. Farmers’ demand, gas supply to the plants, and the regulated or negotiated price of product are the operating levers. It is a different business from an explorer that happens to produce gas, even when gas is the input.',
      'The company is widely held and widely discussed as a dividend name. Discussion is not a declaration. Only the notice states the rate, the face value, and the dates. Between notices, the honest public sentence is that you should read the notice.',
      caution],
    ['Gas, subsidy, and cash',
      'Fertilizer earnings can move with gas availability and with the treatment of subsidies or price decisions. Those are policy facts as much as factory facts. Read the director’s report for how the company described the year’s policy environment, and read the cash-flow statement to see whether the profit was collected.',
      'A high accounting profit that does not become cash will show up as receivables or as another balance-sheet balance. That is the page to linger on.'],
    ['In a personal ledger',
      'If you own FFC for the dividend, your tracker still needs the purchases. The yield you care about is cash received against what you paid, after withholding, not a percentage someone quoted on a forum.',
      'A face-value change, if one occurs, changes the meaning of a percentage dividend. Check the notice’s face value against the face value stored in your notes before you multiply.'],
  ]),

  '/markets/shares/mcb': share('MCB', 'MCB Bank', [
    ['The business',
      'MCB Bank is a listed commercial bank. It takes deposits, extends credit and makes investments, and earns a spread minus credit losses and costs. That is a leveraged balance sheet. It is not analyzed well as if it were a factory with a P/E to sort beside cement.',
      'The bank guide on this site lists the figures that usually matter: deposit mix, net interest margin, non-performing loans and coverage, capital adequacy, and price against book. Use MCB’s own annual report for the figures. This page deliberately has none.',
      caution],
    ['What changes the year',
      'The policy rate moves the spread. Credit conditions move the provisions. A calm year’s low non-performing ratio is a description of that year. The capital ratio tells you how thick the buffer is under the depositors. Read them together.',
      'Dividends from a bank can be regular and can also be shaped by capital needs and by the regulator. Record payments you received. Do not accrue a hoped-for dividend as if it were cash already in the broker wallet.'],
    ['In a personal ledger',
      'MCB shares are lots like any other issuer. There is no special FIFO rule for banks. There is a special reading rule: do not let a single earnings multiple be the whole note you save in the journal.',
      'Reconcile quantity to CDC. Banks do not get a free pass on bonus issues and rights. If the count changed and you did not record why, the cost basis is already wrong.'],
  ]),

  '/markets/shares/mebl': share('MEBL', 'Meezan Bank', [
    ['The business',
      'Meezan Bank is a listed Islamic commercial bank. It provides banking under contracts intended to comply with Shariah screens the bank describes in its own reports. You still have to read those reports. The word Islamic on a door is not your personal conclusion, and it is not this website’s conclusion.',
      'Economically you are still looking at funding, financing, credit quality, and capital. The words on the income lines differ from a conventional bank. Use the bank’s definitions consistently across years instead of forcing a conventional label onto a line the report has named differently.',
      caution],
    ['Screening and the share you buy',
      'Whether MEBL’s own deposits and financing meet a given scholarly standard is a question for the bank’s Shariah material and for the scholar you trust. Whether the share MEBL belongs in your portfolio is a second question, because buying the share is buying the business, and your broker arrangement is a third. The halal-investing guide separates those questions on purpose.',
      'A KMI-style list may include or exclude the name in a given period. Check the dated list. Do not rely on a memory of last year’s constituents.'],
    ['In a personal ledger',
      'Record MEBL trades the same way as any other share: date, quantity, price, fees, broker. Dividends follow the notice. Nothing in the tracker marks the position halal.',
      'If you also hold a Meezan fund, keep it in the fund portfolio. The bank’s shares and the fund’s units are different issuers, different statements, and different NAVs versus prices.'],
  ]),

  '/markets/shares/sys': share('SYS', 'Systems Limited', [
    ['The business',
      'Systems Limited is a listed technology company. It sells IT services, much of them to clients outside Pakistan, so foreign revenue, hiring, and the exchange rate show up in the story beside ordinary operating margins. Confirm the current mix in the latest report. Export shares change.',
      'A services business does not have a kiln or a loan book. Utilization, staff cost, and whether receivables from customers are collected are the industrial facts. A flashy revenue growth number that is not collected is a receivable story.',
      caution],
    ['What to watch in the filings',
      'Read the revenue note, the currency exposure the company itself describes, and the cash-flow statement. Staff costs that grow faster than revenue for several years are a different company from staff costs that scale with delivery.',
      'Valuation multiples on growing exporters can look high next to a bank or a fertilizer plant. That gap is not, by itself, a sell signal or a buy signal. It is a prompt to see whether the earnings are cash and whether the share count is stable. The P/E guide covers the mechanics of the ratio.'],
    ['In a personal ledger',
      'SYS lots are ordinary lots. The ticker is short and easy to confuse with a similarly named fund or a subsidiary if an import uses the long legal name. Check the symbol on the contract note before you accept a scanned row.',
      'A bonus or split in a growth name is also ordinary paperwork. Record it. The chart, if it is unadjusted, can look like a crash that the notice explains in one paragraph.'],
  ]),

  '/markets/funds/meezan-islamic-fund': {
    kind: 'fund',
    title: 'Meezan Islamic Fund',
    seoTitle: 'Meezan Islamic Fund units and NAV',
    description: 'How Meezan Islamic Fund units work, where the NAV comes from, and how to record them. No reprinted NAV.',
    eyebrow: 'Open-end fund',
    h1: 'Meezan Islamic Fund',
    intro: 'Meezan Islamic Fund is an open-end fund managed by Al Meezan Investments, with a mandate aimed at Shariah-screened equities. This page explains the paperwork. It does not reprint today’s NAV or suggest that the fund is suitable for you.',
    sections: [
      ['Units, not shares',
        'You own units. The manager publishes a net asset value. You subscribe and redeem with the manager or its distributors, using the NAV and any load the offering document describes. That is a different mechanic from buying OGDC through a broker, even when the fund itself holds listed shares.',
        'The offering document is the mandate: what the fund may own, which screen it cites, and what it says it will do if a holding falls outside the screen. The fund’s name is not the mandate. A top-ten list in a factsheet is a snapshot, not the policy.',
        caution],
      ['Where the number comes from',
        'MUFAP publishes fund NAVs for the industry. Your unit balance does not come from MUFAP. It comes from the allocation and from the statement. If those units and the tracker disagree, fix the ledger. Do not “correct” it by typing a NAV into the quantity field.',
        'A sales load means the cash you sent and the units you received are not a simple division of cash by the bare NAV. Record both from the allocation note.'],
      ['Distributions',
        'The fund may pay cash, issue units, or both. Bonus units that offset an NAV drop can be a return of your own capital in unit form. Entering them at zero cost makes a later redemption look like a pure profit. Use the statement’s description.',
        'Tax on a fund distribution is not the same form as withholding on a listed company’s cash dividend. The statement and an adviser beat a guess copied from a share you also own.'],
      ['In PSX Tracker',
        'Keep the fund in a fund portfolio so unit math stays away from share lots. Mark it with the published NAV when you want a daily figure, and expect that figure to be a mark, not a withdrawal you can spend without redeeming.',
        'The halal-investing and KMI guides explain why a fund’s screen is a document you read and not a badge this website awards.'],
    ],
    faqs: [
      ['Does this page show today’s NAV?', 'No. Use MUFAP and the manager for the published NAV. This site does not republish that feed.'],
      ['Is the fund halal because of its name?', 'The name tells you the manager’s stated mandate. Your own conclusion depends on the offering document, the screen it cites, and the scholar you trust.'],
      ['How do I record a subscription?', 'Enter the cash you paid and the units you were allotted, including any load, on the allocation date. Keep the PDF.'],
    ],
  },

  '/markets/funds/al-meezan-mutual-fund': {
    kind: 'fund',
    title: 'Al Meezan Mutual Fund',
    seoTitle: 'Al Meezan Mutual Fund units',
    description: 'How to read Al Meezan Mutual Fund’s mandate and record units, without a republished NAV.',
    eyebrow: 'Open-end fund',
    h1: 'Al Meezan Mutual Fund',
    intro: 'Al Meezan Mutual Fund is an open-end fund from Al Meezan Investments and one of the older funds in that range. Confirm the current mandate in the offering document. This page does not reprint a NAV or a return.',
    sections: [
      ['Read the mandate before the factsheet',
        'Factsheets highlight a recent period. Offering documents state what the fund is allowed to own and which limits apply. If those two ever feel different, the document and the latest official update win. Do not rely on a portfolio site to classify the fund for you.',
        'Al Meezan also runs other funds, including Meezan Islamic Fund and money-market or income funds. Similar names are not the same units. A subscription to the wrong fund is a real mistake and a painful redeem. Match the name on the allocation to the name you intended.',
        caution],
      ['Recording units',
        'Store the allocation PDF. It has the date, the NAV used, the units, and the charges. Your cost per unit is cash paid divided by units received. Later redemptions close units. Decide whether you match the oldest units first or keep an average, and stay with that choice.',
        'The statement is the quantity. A tracker that drifts from the statement is wrong even if the NAV it shows matches the newspaper.'],
      ['Returns you did not earn twice',
        'NAV already reflects the portfolio after the manager’s fee. Subtracting the fee again from a NAV change double-counts it. Distributions you received in cash should be recorded as distributions, not as a second copy of the NAV move.',
        'Switching between Al Meezan funds around a distribution date is a tax-sensitive decision. Confirm it with an adviser. The tracker can record the redemption and the new subscription. It should not recommend them.'],
      ['Keeping it apart from the bank',
        'Units of this fund are not shares of Meezan Bank. Different issuer, different statement, different screen. Hold the fund in the fund book.',
        'Reconcile units monthly. It takes minutes and it is the difference between a record and a guess.'],
    ],
    faqs: [
      ['Is this the same as Meezan Islamic Fund?', 'No. They are different funds. Match the full name on your statement before you enter units.'],
      ['Where is the NAV?', 'On MUFAP and in the manager’s material. It is intentionally not copied here.'],
      ['Can PSX Tracker file the fund’s tax?', 'No. It can store the units and the cash events you enter. The statement and your adviser are the tax record.'],
    ],
  },

  '/markets/funds/ubl-stock-advantage-fund': {
    kind: 'fund',
    title: 'UBL Stock Advantage Fund',
    seoTitle: 'UBL Stock Advantage Fund units',
    description: 'What UBL Stock Advantage Fund is, how equity-fund units differ from shares, and how to record them. No NAV reprint.',
    eyebrow: 'Open-end fund',
    h1: 'UBL Stock Advantage Fund',
    intro: 'UBL Stock Advantage Fund is an open-end equity fund from UBL Fund Managers. It invests in listed shares under the mandate in its offering document. This page does not show a NAV, a ranking, or a Shariah status.',
    sections: [
      ['An equity fund is a basket with a fee',
        'The fund holds many shares so you do not have to. You pay for that through the fees in the document, taken inside the NAV. Your result is the change in NAV plus distributions, not the KSE-100’s result. The holdings differ and the fee is real.',
        'It is a conventional equity mandate unless the current document says otherwise. Do not infer a Shariah screen from a familiar ticker in the top holdings. If you need a screen, read an Islamic fund’s policy or the KMI methodology. Do not invent one for this fund.',
        caution],
      ['Paperwork',
        'Subscribe and redeem in units. Keep the allocation. Record loads if any. Mark the holding with the published NAV when you want a figure for today, and remember that a delayed NAV is a blank day, not a zero return.',
        'Distributions are the manager’s event. Record what the statement says you received, in cash or in units, and do not also invent a dividend as if the fund were a single company.'],
      ['Comparing it with owning the shares yourself',
        'Owning the fund means you accept the manager’s portfolio and the fee. Owning a handful of shares yourself means you accept concentration and your own homework. Neither is morally or financially superior on a webpage. The limited-capital guide talks about that choice when the account is small.',
        'You can hold both. Keep the fund in the fund portfolio and the shares in the stock portfolio so the reconciliations stay attached to the right statement.'],
      ['What this site will not do',
        'It will not republish the daily NAV, will not paste a performance league table, and will not tell you the fund is appropriate. UBL Fund Managers publishes the document and the reports. MUFAP publishes the NAV. Your job is to read them if you are considering the units.'],
    ],
    faqs: [
      ['Does the fund track the KSE-100 one for one?', 'No. It is an equity fund with its own holdings and fees. Expect a difference and read the report for the reason.'],
      ['Why is there no performance table here?', 'A copied league table goes stale and pretends to be a promise. Use the manager’s current factsheet if you want their figures.'],
      ['How do I track units I already hold?', 'Enter subscriptions and redemptions from the statements in a fund portfolio, then match the unit count to the latest statement.'],
    ],
  },
};

export const toolPages = {
  '/tools': {
    title: 'PSX portfolio calculators',
    seoTitle: 'PSX portfolio calculators',
    description: 'Capital gain, SIP, zakat, FIFO, dividend yield, and trade charges. You type every number.',
    eyebrow: 'Calculators',
    h1: 'Calculators that use the numbers you type',
    intro: 'These tools do arithmetic for a Pakistan Stock Exchange ledger, a monthly investment plan, and a zakat estimate. They do not fetch a price or a NAV. NCCPL, your broker, and a scholar you trust remain the authorities for tax and zakat.',
    sections: [
      ['Pick a calculator',
        { links: [
          { href: '/tools/capital-gains', label: 'Capital gain on a share sale' },
          { href: '/tools/sip', label: 'SIP future value' },
          { href: '/tools/zakat', label: 'Zakat estimate' },
          { href: '/tools/fifo-vs-average', label: 'FIFO versus average cost' },
          { href: '/tools/dividend-yield', label: 'Dividend yield' },
          { href: '/tools/trade-costs', label: 'Commission and CDC charges' },
        ] }],
      ['What they refuse to do',
        'They will not look up a live share price or today’s gold rate. You type those. The capital-gains tool applies the Finance Act 2025 schedule for listed shares, which a later budget can replace. NCCPL’s bill is the one that is collected.',
        'They also will not place a trade. When you want a record rather than a one-off sum, enter the fill in the app and keep the contract note.'],
    ],
    faqs: [
      ['Are these official tax calculators?', 'No. They multiply the figures you enter. NCCPL computes securities capital gains in the ordinary regime. An adviser interprets your case.'],
      ['Why not pull the live price?', 'So the page does not republish market data, and so a stale quote cannot masquerade as the price you would have got.'],
      ['Can I save the result?', 'The result stays on the page. A lasting record belongs in your portfolio, next to the contract note.'],
    ],
  },
  '/tools/capital-gains': {
    form: 'capital-gains',
    title: 'Share capital gain calculator',
    seoTitle: 'PSX capital gain calculator',
    description: 'Estimate CGT on one PSX share sale for a filer and a non-filer, from the dates and prices you type.',
    eyebrow: 'Calculator',
    h1: 'Capital gain on a share sale',
    intro: 'Enter one purchase and one sale. The tool shows the gain, then the Finance Act 2025 rate for someone on the Active Taxpayers List and for someone who is not. Holding period and the buy date decide the rate. This is one trade, not NCCPL’s yearly net.',
    sections: [
      ['How the arithmetic works',
        'Proceeds are the sale price times quantity. Cost is the buy price times quantity plus the buy fees you enter. Gain is proceeds minus sell fees minus that cost. If the gain is negative, the estimate of tax at a positive rate is zero in this simple tool. Real loss treatment is a question for your adviser, not a minus sign we invent rules for.',
        'A partial sale that closes several lots is not this form. Use the FIFO comparison, or the app’s lot book, when the shares you sold were bought on more than one date.'],
      ['Worked illustration',
        'Five hundred shares bought at 100 with 200 in buy charges, sold at 130 with 250 in sell charges: proceeds 65,000, cost 50,200, gain 14,550. If those shares were bought on 1 August 2024, the schedule’s rate is 15% on the Active Taxpayers List and 30% off it. Shares bought on or after 1 July 2025 are 15% either way.'],
    ],
    faqs: [
      ['Why do the two rates differ?', 'For shares bought before 1 July 2025, someone off the Active Taxpayers List is often charged more. Shares bought on or after that date are 15% in this schedule either way. A later Finance Act can change the table.'],
      ['Does this match NCCPL?', 'Not necessarily. NCCPL has the official computation. This is personal arithmetic so you can see the gain before that computation.'],
      ['Where do fees go?', 'Buy fees sit in cost. Sell fees reduce proceeds. Leaving them out makes the gain look larger than the contract notes.'],
    ],
  },
  '/tools/fifo-vs-average': {
    form: 'fifo-vs-average',
    title: 'FIFO versus average cost',
    seoTitle: 'FIFO vs average cost calculator',
    description: 'See how a partial PSX sale changes gain when oldest lots are sold first instead of a blended average.',
    eyebrow: 'Calculator',
    h1: 'FIFO versus average cost',
    intro: 'Enter two buy lots, oldest first, and a partial sale. The tool closes the oldest shares first, then shows the gain you would get from a single blended price. The difference is why a broker’s average and a FIFO ledger disagree.',
    sections: [
      ['What is being compared',
        'FIFO asks which shares you sold. Average cost asks what the remaining pile cost in total and spreads that across every share. On a partial sale those are different gains. Neither figure files your tax. They explain a personal book.',
        'The default shape of the example in the FIFO guide is 100 shares at 200, then 100 at 170, selling 50 at 225. Oldest-lot cost is 200, so the FIFO gain is driven by 225 minus 200. The blended price is lower, so the average-cost gain is larger. Type those numbers if you want to see it move.'],
    ],
    faqs: [
      ['Which method does NCCPL use?', 'Do not take a calculator’s method as the filing method. Ask the official material and your adviser. This page only shows that the two personal methods diverge.'],
      ['Can I enter more than two lots?', 'This public form takes two. The app’s ledger handles a longer stack, including transfers and same-day buys.'],
      ['What if I sell more than I bought?', 'The tool stops. It will not invent a cost for shares that were not in the lots.'],
    ],
  },
  '/tools/dividend-yield': {
    form: 'dividend-yield',
    title: 'Dividend yield calculator',
    seoTitle: 'Dividend yield calculator',
    description: 'Divide an annual dividend per share by a price you type. No live PSX quote is fetched.',
    eyebrow: 'Calculator',
    h1: 'Dividend yield from numbers you supply',
    intro: 'Yield is the annual cash dividend per share divided by a price, expressed as a percentage. You type both. A yield without a price date and a dividend date is not something you can compare with a friend’s screenshot.',
    sections: [
      ['What to type',
        'Use the dividend you are actually measuring: last year’s cash dividends per share, or the latest declared rate converted with the face value in the notice, if that is the question you mean. Say which one in your notes. A percentage declaration is not a rupee amount until you apply the face value printed on that notice.',
        'Use a price you choose: the price you paid, or a close you read on your broker on a date you write down. This page will not fetch one. Withholding tax means the cash you received is smaller than the declared dividend. A yield on the gross dividend overstates the cash yield.'],
    ],
    faqs: [
      ['Does a high yield mean a cheap stock?', 'No. Yields rise when prices fall and when a dividend is about to be cut. Read the notice and the accounts.'],
      ['Should bonus shares be in the yield?', 'No. Bonus shares are not cash. Record them as shares. This calculator is only for a cash dividend per share.'],
      ['Why might my yield disagree with a website?', 'Different price dates, gross versus net, and face value after a split. Their feed is not more official than the company notice plus the price you actually used.'],
    ],
  },
  '/tools/trade-costs': {
    form: 'trade-costs',
    title: 'Trade cost calculator',
    seoTitle: 'PSX commission and CDC calculator',
    description: 'Add a commission, tax on that commission, and a CDC amount from your own broker schedule.',
    eyebrow: 'Calculator',
    h1: 'Commission and CDC charges',
    intro: 'Type the trade value and the rates from the fee card in front of you. Schedules change and differ by broker. This tool does not store a broker’s rates and will go stale if it tried.',
    sections: [
      ['The three lines',
        'Commission is a percentage of trade value you type. Sales tax here means a percentage applied to that commission, which is how many Pakistani schedules present it, not a tax on the whole trade. The CDC or clearing line is an amount you type, in rupees, because it is often a small fixed or schedule-based figure you should read rather than remember.',
        'If your schedule has more lines, add them into the CDC box for a rough total or do the extra line on paper. A rough total that you understand beats a precise total from a copied card that expired last year. The broker guide explains how to ask for the real schedule.'],
    ],
    faqs: [
      ['Which broker’s rates are built in?', 'None. If a calculator ships with a hidden rate, it is wrong for someone on the day the broker revises the card.'],
      ['Is sales tax the same as capital gains tax?', 'No. This box is tax on the commission. Capital gains tax is on the profit of a disposal and is estimated on the capital-gains calculator.'],
      ['Does this include the spread?', 'No. The price you accept versus the price you hoped for is part of the trade, but it is not on the fee card. Include it in your own judgment of the fill.'],
    ],
  },
  '/tools/sip': {
    form: 'sip',
    title: 'SIP calculator',
    seoTitle: 'SIP calculator',
    description: 'Project a monthly investment from an annual return you type. The result is an assumption, not a forecast.',
    eyebrow: 'Calculator',
    h1: 'SIP future value',
    intro: 'A systematic investment plan here means a fixed rupee amount invested at the start of each month. You type the amount, how many years, and the annual return you want to assume. The tool does not know what a fund will earn.',
    sections: [
      ['What the number is',
        'Each monthly amount is assumed to earn the monthly equivalent of the annual rate you typed, compounded for the months left. Money you already hold is grown for the whole period. The total you put in is shown beside the estimate so the gap is visible.',
        'A zero return simply adds the contributions. A negative return is allowed, because a fund can fall. A return of −100% or worse is rejected because the monthly rate stops making sense.'],
      ['What it is not',
        'It is not a mutual-fund factsheet and it does not fetch a NAV. Loads, management fees, and a missed month are not inside the formula unless you have already folded them into the return you typed. Past performance of a fund is not this page’s input.',
        'Use it to see how sensitive a plan is to the rate. Run it twice, with a modest rate and a poor one, before you treat either figure as a goal.'],
    ],
    faqs: [
      ['Does this guarantee the return?', 'No. The percentage is yours. The tool only compounds it.'],
      ['When is the money assumed to be invested?', 'At the start of each month, so the first contribution has the whole month’s assumed growth.'],
      ['Can I track a real SIP in the app?', 'Yes. Record each subscription from the fund statement in a fund portfolio. This page does not write to that ledger.'],
    ],
  },
  '/tools/zakat': {
    form: 'zakat',
    title: 'Zakat calculator',
    seoTitle: 'Zakat calculator',
    description: 'Estimate 2.5% zakat from cash, gold, silver, and investments you type, once they reach nisab.',
    eyebrow: 'Calculator',
    h1: 'Zakat estimate',
    intro: 'This applies 2.5% to the zakatable net you enter, if that net reaches nisab. Nisab is measured as 612.36 grams of silver or 87.48 grams of gold, at a price per gram you type. It is not a fatwa, and it does not look up today’s metal rate.',
    sections: [
      ['What you add up',
        'Cash and bank balances, gold and silver you hold, and the rupee value of shares or fund units you have decided are zakatable. Some scholars calculate zakat on trading shares at market value, and on long-term shares only on the company’s zakatable assets. This form uses the rupee amount you type, so that choice stays yours.',
        'Debts you enter are subtracted. Scholars differ on which debts count. If you are unsure, leave the debt line at zero and ask before you deduct.'],
      ['Nisab and the rate',
        'Silver nisab is the lower bar, so more people cross it. Gold nisab is higher. Pick the measure your scholar uses, and type that metal’s price per gram even if you do not hold any of it. If the net is below nisab, the estimate is zero. If it is at or above nisab, zakat is 2.5% of the whole net, not only of the amount above the line.',
        'The lunar year is not calculated here. Zakat is due on wealth that has been in your hands for a lunar year, on the conditions you follow. Crossing nisab on the day you fill in the form is not, by itself, the due date.'],
    ],
    faqs: [
      ['Is this a religious ruling?', 'No. It is arithmetic at 2.5% with a nisab weight that is widely used. A scholar you trust applies it to your case.'],
      ['Why type a metal price?', 'So the page does not republish a live gold or silver quote. Use a price you have checked, and note the date.'],
      ['Do I include my house and my car?', 'Personal use assets are commonly excluded. This form does not add them. Add only what you are treating as zakatable.'],
    ],
  },
};
