/** Extra sections appended to thin guides. Original pages stay intact. */
export const guideDepth = {
  'fifo-cost-basis-psx': [
    ['Corporate actions and partial sells',
      'A bonus issue, a rights issue, or a stock split changes the number of shares without a normal buy. If you only store an average price and then apply FIFO later, the lot stack no longer matches the contract notes. Record the corporate action on the date the shares arrived, with the cost treatment you and your adviser agree, and keep the company notice beside the entry.',
      'Partial sells across several years are where homemade sheets usually break. The oldest open lot might be from a different face value, a different broker, or a transfer in from another account. PSX Tracker consumes lots in date order, including transfer-ins, so a later sell does not silently use a blended price. If the quantity you sell is larger than the open lots, the ledger should show that gap instead of inventing a cost.',
      'When you move shares between your own portfolios, the destination should keep the source lot’s cost, not a fresh market price. A market-price transfer would create a fake gain on a day you did not sell to anyone else.'],
  ],

  'start-investing-on-psx': [
    ['After the first month',
      'The first fill is the easy part. The useful habit is the one you repeat: save the contract note, enter the trade the same week, and check that the quantity in your tracker matches the CDC or broker position. A month of clean records is worth more than a year of reconstructed guesses.',
      'Decide in advance what “enough research” means for you before a second purchase. That can be as simple as reading the latest annual report’s business description, the debt note, and the dividend history, then writing one sentence on why you own it. Tips from a group chat are not that sentence.',
      'If the account is small, costs matter more than the index story. A high commission on a tiny order can erase a modest move. The limited-capital guide walks through that tradeoff, and the broker guide is the place to compare how you will actually fund and export the account.'],
  ],

  'cgt-basics-pakistan-stocks': [
    ['What counts as a disposal',
      'A disposal is the sale or other transfer that closes shares, not the day you withdraw cash from the broker. You can sell shares and leave the proceeds in the broker wallet. You can also withdraw cash that came from a deposit, a dividend, or an older sale. Only the closing of lots creates a capital gain or loss for that trade.',
      'Gifts, transfers between your own accounts, and inheritance are not ordinary market sells. Treat them as their own events and ask a tax adviser which cost carries over. Recording them as a sale at the market price will invent a gain you did not earn from a buyer.',
      'Same-day buys and sells need care. If the sell is listed before the buy in a file, a naive ledger can claim you sold shares you did not yet hold. A usable book applies the day’s purchases before it closes lots, then reports only the quantity that was actually open.'],
    ['Build the file you would hand an adviser',
      'For each sell, an adviser eventually wants the date, symbol, quantity, sale price, sale charges, and the buy dates and costs of the lots that sale closed. Contract notes and CDC statements are the originals. A tracker is the index that makes those originals searchable.',
      'Keep dividends and withholding in a separate column from share sales. A cash dividend is income, not a capital gain, even when it lands in the same broker wallet. Mixing the two makes both the tax conversation and your personal return harder to explain.',
      'Export the ledger after a large disposal and tick it against the contract note before you rely on the figure. Duplicated imports are the usual error: the same fill entered twice doubles the quantity and the gain. The reconcile guide covers that check.'],
    ['Holding period is a date problem',
      'Pakistan’s treatment of listed-share gains has depended on how long the shares were held and on the rules for that tax year. The percentage is not a constant you should copy from an old post. What you can prepare, any year, is the dates. FIFO makes the holding period of a partial sell a fact instead of a guess, because you know which lot closed.',
      'Filer and non-filer status, funds versus shares, and debt securities are different questions. This guide is about listed shares you bought and sold through a broker. Mutual-fund redemptions follow the fund’s distribution and the statement the asset manager issues.',
      'PSX Tracker can show a realized gain from the lots and fees you entered. It does not submit a return, apply an exemption, or know which ordinance applies to your year. Use the public capital-gains calculator only as arithmetic on numbers you type. NCCPL’s computation and your adviser remain the authority.'],
    ['A labeled illustration, not a filing',
      'Suppose you bought 500 shares at 100 and paid 200 in buy charges, then sold all 500 at 130 and paid 250 in sell charges. Proceeds are 65,000. Cost is 50,200. Gain after the sell charge is 14,550. That arithmetic is the personal record. The tax is 14,550 multiplied by whatever rate actually applies to that holding period and tax year, and only if the gain is taxable in your situation.',
      'If you had bought 200 shares earlier at 80 and 300 later at 110, a partial sale of 200 shares does not use the blended price. FIFO closes the earlier lot first. Average cost would report a different gain from the same contract note. The FIFO guide works that contrast with another set of round numbers.',
      'Write the illustration’s result next to the contract note, not instead of it. If the two disagree, the contract note wins and the ledger needs a correction.'],
    ['Habits that survive a rule change',
      'Save the PDF when the trade fills, not at tax time. Name it with the date and symbol so you can find it. Enter the trade, including fees, in the same week. Once a month, match open quantities to the broker.',
      'When a budget announcement changes a rate, your old ledger is still useful. Dates and costs do not expire. Only the rate you apply on top of them changes. That is why a tracker should store the trade, not a hardcoded tax percentage.',
      'If you are unsure whether a corporate action, a gift, or an off-market transfer is a disposal, stop and ask. Guessing inside the app creates a number that looks precise and is wrong. The app is a notebook. It is not the Federal Board of Revenue and it is not NCCPL.'],
  ],

  'choosing-a-psx-broker': [
    ['Licensing before convenience',
      'Start from the register, not from an advertisement. A firm that can broker PSX trades is registered for that activity. SECP and PSX publish ways to confirm a broker. A WhatsApp contact who offers “guaranteed lots” and asks you to transfer money to a personal account is not a shortcut. It is a reason to stop.',
      'The brand on the app store is not the same check. Read the legal name on the account-opening form and match it to the registered name. If the form and the advertisement disagree, use the form’s name for the register search.',
      'You can hold accounts at more than one broker. Many investors do, then struggle to see one portfolio. A tracker that records the broker on each trade lets you keep the books separate and still look at the combined holdings. The broker’s own app remains the place you place orders.'],
    ['What the fee card actually contains',
      'Commission is the line people compare, and it is rarely the only line. A schedule can also include a tax on the commission, CDC or clearing charges, and other regulatory amounts. The names and the rates change. Print or save the schedule on the day you open the account, and save it again when the broker emails a revision.',
      'A lower commission on a huge notional can still be a poor deal if withdrawals are slow or statements are unusable. A slightly higher commission with a clean CSV and a same-day contract note can be cheaper in the hours you will spend reconstructing a year of trades.',
      'Do not publish someone else’s fee table as if it were permanent, and do not trust one you memorized last year. The trade-cost calculator on this site adds the commission, the tax on that commission, and a CDC amount you type from your own schedule. It does not store a broker’s current card.'],
    ['Funding, withdrawals, and whose account it is',
      'Client money should move on the broker’s published funding instructions, into an account in the broker’s client-money name, from a bank account in your name. If a representative asks you to use their personal wallet “just this once,” refuse.',
      'Try a small withdrawal before you need a large one. The test is whether the money returns to the same bank account, in a stated number of days, without a new set of unofficial charges. Note the date and the amount in your own ledger so the cash balance stays explainable.',
      'Joint accounts, company accounts, and accounts for someone else have their own paperwork. Do not place a relative’s trades inside your login and hope to sort the beneficial owner later. The CDC sub-account name is part of the record.'],
    ['Statements you can actually reconcile',
      'Before you fund a large amount, ask how you will download contract notes, a period statement, and a holdings list. A PDF that you can save is the minimum. A CSV or spreadsheet export saves a weekend when you import history into a tracker.',
      'Check one sample statement for the fields you need: trade date, symbol, buy or sell, quantity, price, commission, and other charges. If the symbol is missing or the date is ambiguous, you will mis-key the ledger. Day-first and month-first dates are a common way to land a trade in the wrong month.',
      'After the first ten trades, reconcile. Open quantity in the tracker should match the broker. Cash should match deposits, withdrawals, buys, sells, dividends, and fees, with transfers between your own portfolios left out of the cash story. If it does not match, fix the entry while you still remember the trade.'],
    ['App quality is a safety feature',
      'You will place orders on a phone, in a moving market. An app that hides the order type, the limit price, or the symbol you are about to buy is a source of errors, not a convenience. Practice with a small limit order and confirm the contract note the same day.',
      'Support matters on the day a deposit does not show or a symbol looks wrong. Note the hours, the language, and whether you can reach a person. A community forum is not the broker’s complaint process.',
      'PSX Tracker does not choose a broker and does not receive your order. Use this guide as a checklist, confirm the firm on the official register, and keep the contract notes. The portfolio app starts after the fill exists.'],
  ],

  'is-psx-investing-halal': [
    ['Separate the market from a single share',
      '“Is the stock market halal?” is several questions wearing one coat. There is the question of buying and selling ownership in a business. There is the question of whether that business’s activity is acceptable. There is the question of interest-bearing debt, interest income, and other financial ratios that screening bodies publish. And there is your own contract with the broker, including how the account is funded.',
      'A yes or no about “PSX” as a building does not answer any of those. The exchange is the venue. The share is a claim on a company. Two companies listed on the same day can sit on opposite sides of a screening list.',
      'This page will not give you a ruling. A ruling is personal and belongs with a scholar you trust, using the company’s current accounts and the method that scholar uses. What follows is a map of the questions investors in Pakistan commonly take to that conversation.'],
    ['Business activity comes first',
      'Screening methods usually start with what the company does. A firm whose main business is alcohol, conventional interest-based lending, gambling, or another excluded activity is out before anyone divides debt by assets. Read the principal-activity note in the annual report, not the slogan on the homepage.',
      'Conglomerates are harder. A listed holding company can own an acceptable business and a stake in something a screen would exclude. The method you follow will say whether the segment size matters and how the stake is counted. Do not average the segments yourself and call it a ruling.',
      'A company can also change. A new subsidiary, a discontinued plant, or a shift in revenue can move it across a line between one published list and the next. The list date is part of the answer. A screenshot without a date is not a source.'],
    ['Debt, interest, and the ratios people quote',
      'After the business test, published Shariah equity screens often look at interest-bearing debt, interest income, and illiquid assets, each as a share of something defined in the methodology. The thresholds are not universal. One method’s cutoff is not another method’s cutoff, and both can be revised.',
      'The inputs come from the financial statements, and the statements are not self-interpreting. “Borrowings” can include more than one kind of facility. Cash can include balances held for customers. If you compute a ratio, write down the line items and the page numbers. If you cannot, you do not yet have a ratio. You have a rumor.',
      'Traders sometimes treat a low debt number as a moral conclusion. It is an input. Liquidity, receivables from a related party, and what the company does with surplus cash can matter under the method you follow, even when the headline debt looks small.'],
    ['KMI-style lists are a publication, not a personal fatwa',
      'Pakistan’s KMI-style indexes publish a rules document and a list of constituents. The list is useful because someone has applied a written method to a dated set of accounts and named the result. It is not useful as a substitute for reading the method, and it is not a statement about your personal duty.',
      'A share can enter or leave the list when the accounts change or when the rules change. Buying because a ticker was on last year’s list, without checking this year’s notice, is how people get surprised. The KMI guide on this site describes how to read those publications carefully.',
      'A portfolio app can show a sector and a research page. It cannot know which scholar you follow or whether your financing of the purchase is acceptable. Meezan Bank being an Islamic bank, or a fund having “Islamic” in its name, does not automatically make every holding in your personal account compliant.'],
    ['Your broker, your cash, and the trade itself',
      'Some investors care how the brokerage account holds idle cash, whether any facility extended to them bears interest, and whether a conventional margin product is attached to the login. Those are questions for the broker’s terms and for your scholar. They are not visible in the share price.',
      'Speculation is a separate moral discussion from the company’s business. Short-term trading, leverage, and tips are not answered by an index factsheet. If your rule is “I only buy businesses I can describe, with money I can leave invested,” write that down and check your ledger against it.',
      'PSX Tracker can keep the names you chose to own, the dates, and the dividends. It does not label a ticker halal or haram, and it should not. Use the company filings, the screening methodology you accept, and a qualified person. Then record the decision you actually made.'],
  ],

  'tracking-psx-dividends': [
    ['Three different events that all get called a dividend',
      'A cash dividend sends money. A bonus issue sends extra shares. A dividend reinvested at a fund sends extra units. They all come from a distribution announcement, and they do not belong in the same column. Cash increases the cash balance. Bonus shares increase quantity and usually change the cost per share. Reinvested units increase the fund holding.',
      'Withholding tax is a fourth number. The company or the fund may pay you the net amount and remit tax on your behalf. If you record only the cash that arrived, you understate the dividend and you lose the tax already suffered. Record gross, tax, and net. The cash book should move by the net. The income book should show the gross.',
      'Face value is part of the announcement when a company declares a percentage. “100 percent” means something different after a share splits or the face value changes. Read the notice for the face value it uses, and do not multiply a percentage by an old face value because a spreadsheet still has 10 in a cell.'],
    ['Dates: announcement, book closure, and payment',
      'You do not earn a dividend by owning the share on the day you hear the rumor. Companies announce a rate, a book-closure window, and later a payment. The holder on the register for that book closure is the person the company pays. Buying after you have missed that window does not catch the payout, even if the price has not yet fallen.',
      'The ex-date idea is the market’s way of saying the new buyer will not receive this distribution. Prices often adjust. Your personal gain calculation should not treat that price drop as a mysterious loss if you also received the cash. The cash is in a different column. The shares you still hold are marked at the new price.',
      'Payment can lag the announcement by weeks. Do not enter the cash on the announcement date unless the money is already in the broker wallet. Enter it when you receive it, and keep the announcement date in the note so you can match the company notice.'],
    ['Bonus shares and the cost stack',
      'Bonus shares are not free in the sense that your wealth doubled. You own more shares of the same company, and the price typically adjusts. For a personal FIFO book, you need a rule for the cost of the new shares. Many investors spread the existing cost across the new total quantity so the total cost does not jump. Write the rule down and apply it the same way every time.',
      'A rights issue is different again. You pay for the new shares. That payment is a real cost and belongs in the new lot at the price you paid, plus charges. Ignoring the cheque and only adding the quantity makes every later sale look more profitable than it was.',
      'If you skip the corporate action and only change the quantity to match the broker, the average cost on screen will be wrong even when the share count is right. Match both quantity and cost to the statement after every book closure you participated in.'],
    ['Funds distribute differently from companies',
      'An open-end fund may pay cash, issue bonus units, or both. Bonus units that restore the NAV after a distribution are often your own capital coming back as units, and the tax treatment is not the same as a cash dividend from a listed company. The fund’s statement and the category of the fund matter. Do not copy the share-dividend habit across.',
      'Someone who wants the fund’s growth without the distribution will sometimes switch categories around an announcement. That is a tax-sensitive decision, not a tracker trick. Confirm it with an adviser. The app can record the switch you made. It should not recommend the switch.',
      'MUFAP publishes NAVs. It does not tell you that you personally received a dividend. Your asset-manager statement does. Use the statement for the units and the cash, and the NAV only to mark what you still hold.'],
    ['Where the money shows up in a portfolio',
      'Total return is price change plus income, minus what you paid away in costs and taxes. A portfolio that ignores dividends will look worse than the investor’s actual result, especially for companies that pay a large share of their return in cash. A portfolio that counts the dividend and also counts a withdrawal of that same cash as a loss will look worse twice.',
      'In PSX Tracker, a cash dividend increases cash. It is not a capital gain and it is not a deposit of new savings. A withdrawal is you taking cash out. Keeping those three events apart is what makes “how much did I invest?” a different number from “what is the account worth?”',
      'Once a quarter, list the dividends you think you were owed and tick them against the bank or broker credits. Missed dividends are usually a book-closure date you misunderstood, a bonus you recorded as cash, or a fund distribution you never entered. The export-and-reconcile guide is the checklist for that afternoon.'],
  ],
};
