/** Further guide sections. Merged with guideDepth in guidePages.js. */
export const guideDepthMore = {
  'mutual-fund-nav-tracking': [
    ['Units, NAV, and why a fund is not a share',
      'An open-end fund does not have a board lot. You own units. The asset manager publishes a net asset value, usually once each business day, and you buy or redeem with the manager or its distributor rather than by hitting a bid on the exchange. Some funds are also listed, but the daily NAV is still the figure the statement uses for the open-end book.',
      'NAV is the value of the portfolio minus liabilities, divided by the units in issue. It is not a promise of the next day’s price, and it is not the amount you will receive if a charge applies on the way out. Read the offering document for the sales load, the backend load, and the management fee before you treat NAV as cash in hand.',
      'MUFAP publishes industry NAVs so investors can see a common figure. PSX Tracker can mark a fund portfolio from that kind of published NAV. Your own unit balance still comes from the account statement. If the statement says 1,000 units and the app says 1,040, the NAV is not the problem. The ledger is.'],
    ['Cost of units, including the charges you paid',
      'The amount you transferred is not always the amount that became units. A sales load, if the fund charges one, means fewer units than a naive division of cash by NAV. Record the units from the allocation note and the cash you paid. The cost per unit is cash paid divided by units received, not the bare NAV on the day you decided to invest.',
      'Later redemptions close units. If you bought on three dates, a partial redemption has the same lot question as a share sale. Decide whether you match the oldest units first or keep an average, write it down, and stay with it. Mixing the two methods between years makes the realized number incomparable with itself.',
      'Reinvested distributions add units at a cost you need to define. Bonus units that offset an NAV drop are often a return of your own capital in unit form. Entering them at zero cost makes a later redemption look like a pure gain. The fund statement is the place to see how the manager described them.'],
    ['Daily P&L is a mark, not a withdrawal',
      'Day-over-day fund P&L is yesterday’s units marked at yesterday’s NAV versus today’s units marked at today’s NAV, with care for units you bought today. A new subscription should not be reported as a profit. The cash left your bank and became units. The profit, if any, is the later change in NAV.',
      'NAVs are not published on the same clock as a share trade. A holiday, a delayed file, or a fund that strikes NAV at a different cut-off can leave a day blank. A blank day is not a zero return. Leave it blank and wait for the published figure rather than copying the previous NAV and calling it a move.',
      'Comparing a fund’s day to the KSE-100 day is only fair when both numbers are the same kind of thing. The index is a price basket. An income fund’s NAV can move because of accruals and a dividend. Read the category before you decide the fund “lagged the market.”'],
    ['Categories change the question you are asking',
      'Equity funds, income funds, money-market funds, and asset-allocation funds do not exist to do the same job. An equity fund will swing with shares. A money-market fund should not, and if it does you want to know why. The offering document and the latest factsheet state the category and the benchmark the manager chose.',
      'Shariah-compliant fund names tell you the manager’s mandate, not your personal conclusion. Read the screening policy in the document. The halal-investing guide explains why a name and a list are not a ruling.',
      'Switching from an income fund to a money-market fund around a distribution date is a tax-sensitive habit some investors discuss. It is not a feature to toggle casually. Confirm the current treatment with an adviser, then record the redemption and the new subscription as two events with two unit prices.'],
    ['Reconcile the fund the way you reconcile shares',
      'Once a month, match units, cost, and cash. Units come from the statement. Cost comes from your subscriptions minus redemptions, adjusted for the corporate actions you recorded. Cash in a stock portfolio is a different wallet from money you sent the asset manager. Do not merge them and then wonder why the stock cash looks negative.',
      'Keep the allocation email or PDF. It has the date, the NAV used, the units, and the charges. A year later you will not remember whether the load was waived. The PDF will.',
      'PSX Tracker keeps fund portfolios separate from share portfolios so unit math and share lots do not overwrite each other. A combined view can sit on top. The statements underneath stay separate, which is what you want on the day one of them disagrees.'],
  ],

  'google-drive-backup-restore': [
    ['What is in the snapshot, and what is not',
      'The Drive file is your portfolio: portfolios, transactions, settings the app chooses to save, and a small cache of panel text so screens can paint while they refresh. It is not a copy of the entire market. Price history is large and stays out of the backup on purpose, so the file you own does not grow without a limit.',
      'A very large pasted statement can also stay on the device only. The backup has a size cap per entry so one import cannot crowd out the transactions. If something you expected is missing after a restore, check whether it was a market cache or an oversized paste rather than a trade.',
      'API keys you typed into the app, including a Gemini key, can ride along in the settings. Treat the Drive file as private. Do not drop it in a shared folder or email it to yourself on a work account you do not control.'],
    ['Pending saves and the revision you think you have',
      'The app saves on a short delay so typing does not upload every keystroke. If you go offline in that window, the change waits on the device. The next successful save should send that waiting copy if the Drive revision is still the one you started from.',
      'If another device saved in the meantime, you have a conflict, not a silent overwrite. The message is that a newer version exists. Read it. Do not mash restore until you have downloaded the copy you are afraid of losing. A restore that replaces the cloud file with an older one will drop the trades that other device added.',
      'The practical habit is one writer at a time for a big edit. Phone and laptop can both read. Simultaneous entry is how two deposits become one, or how a sell on the phone disappears under a laptop that was open all afternoon.'],
    ['Download before you restore',
      'Restore means “make this file the current one.” It is the right tool when you know the cloud copy is the good copy and the device is wrong. It is the wrong tool when you are unsure. Download the JSON first, open it enough to see that the transactions are there, and keep that file somewhere outside the app.',
      'The app also keeps a limited run of older committed versions and tries to bin the older ones. That history is a courtesy, not an archive policy you should bet a decade of trades on. Your own exported file, named with the date, is the archive.',
      'After a restore, check three numbers before you relax: the number of transactions, the cash balance, and one recent trade you remember. If any of the three is wrong, stop and use the file you downloaded. Do not enter new trades on top of a bad restore.'],
    ['Signing in is not the same thing as Drive access',
      'You can sign in with Google or with email and a password. Drive access is a separate permission. Password login can reopen a portfolio on another device only when remembered Drive access is still connected and still approved by Google. If you revoke the app in your Google Account, the remembered credential stops working, which is what you want.',
      'Signing out clears the session on that device. It does not delete the Drive file. Deleting the app’s file in Drive is a separate, deliberate act. Read the privacy page before you do it, and export first.',
      'Shared family computers need the same care as a shared spreadsheet. Sign out when you stand up. The backup is only as private as the Google account it sits in.'],
    ['When the backup and the broker disagree',
      'Drive is a copy of what you entered, not a copy of the broker. If the broker shows 1,000 shares and the restored file shows 800, the broker and the contract notes are the source. The file is wrong, or the broker is showing a corporate action you never recorded. Fix the ledger. Do not “fix” the broker to match an old JSON.',
      'Use the export-and-reconcile guide for the line-by-line check. Use this guide for the mechanics of saving and restoring. They solve different failures, and doing a restore in the middle of a reconcile can destroy the comparison you were about to make.',
      'If a save fails repeatedly, download the pending copy and keep trading records in a spreadsheet until the upload works. A week of unsent trades is recoverable. A week of unsent trades that you then overwrite with last month’s file is not.'],
  ],

  'psx-charts-in-app': [
    ['What the chart is allowed to claim',
      'A candlestick is a picture of prices the app was able to fetch: open, high, low, and close for a period, or a shorter series when that is all that exists. It is not the exchange’s official tape, and it can be delayed, missing, or revised. Before you place an order, the price that matters is the one on your broker’s order ticket.',
      'Indicators are arithmetic on that history. A moving average, RSI, or Bollinger band does not know the company’s news, the dividend that goes ex tomorrow, or the halt you have not heard about. They describe the path the price already took.',
      'The chart can also show your own position: what you paid and what you have realized. That overlay is only as good as the trades you entered. A wrong quantity in the ledger becomes a wrong line on the chart. Fix the ledger first if the picture looks impossible.'],
    ['Choose a question before you choose an indicator',
      '“Is this name in a longer downtrend?” is a different picture from “what did it do this week?” A one-day view that is a single live point will not answer the first question. A five-year view will hide the level you care about for tomorrow’s order. Pick the range that matches the decision, then stop adding indicators until you can say what a cross or a band would change in that decision.',
      'Comparing your chart to a friend’s screenshot is a good way to argue about nothing. Their range, their adjustment for a split, and their data vendor can all differ. Compare both of you to the company’s own filing and to the broker’s chart if the level is important.',
      'Drawings and saved layouts are personal notes. They do not travel as investment advice, and they do not update when you are wrong. If a trend line you drew last year is still on the chart, ask whether it still marks a decision or whether it is decoration.'],
    ['Portfolio context without mixing up the P&L',
      'Seeing cost on the chart helps you remember that “the price is up today” and “I am ahead on this lot” are different. Today’s move uses the previous close, or the trade price if you bought today. Your profit uses the cost of the shares you still hold. The app keeps those calculations apart on purpose.',
      'A chart of the index next to a chart of one stock is context, not a verdict. A stock can fall on a day the KSE-100 rises because of one announcement. Your holdings’ day can differ from both because of what you bought this morning. The performance guide and the dashboard are the place for that comparison. The chart is the place for the price path.',
      'Funds do not belong on a share candlestick. Mark a fund with its NAV series if you have one, and do not paste a fund into a stock chart because the symbol field was empty.'],
    ['Corporate actions and bad candles',
      'A split or a bonus can look like a crash if the history is not adjusted and you do not know the notice. Before you conclude that a company lost half its value overnight, read the announcements for that date. The filings panel exists for that check.',
      'A single absurd high or low is often a bad print. One candle that is ten times the neighbors should make you suspicious of the data, not excited about a signal. Cross-check the broker or the exchange disclosure before you trade the spike.',
      'Missing days are usually holidays or a symbol that did not trade. Filling them with a copy of the previous close and then running an indicator will invent smoothness the market did not have. Leave the gap visible.'],
    ['A research routine that stays honest',
      'Open the company, read what it does, look at the latest results, then look at the chart. The reverse order, chart first and story later, is how people buy a shape. Write down the level at which you would be wrong, in rupees and in reasons, before you size the trade.',
      'Use alerts if you want the app to tell you that a price you chose has been touched. An alert is not an order. You still go to the broker, and you still check that the symbol and the side are the ones you meant.',
      'Nothing on the chart is a recommendation from PSX Tracker. The tool draws the series it can fetch and the trades you stored. The decision, and the mistake, stay with you.'],
  ],

  'free-vs-paid-trial': [
    ['What the trial is for',
      'The trial is a full look at the product after the owner approves the account, so you can import real history and see whether the ledger matches your broker before you pay. It is not a sample made of fake trades. Use your own records. A demo portfolio hides the import problems you actually have.',
      'The homepage states that the trial does not require a card. You should not be asked for a card number to start it. Payment for a Paid plan, if you choose one later, follows the instructions in the app and is a separate step.',
      'Approval is manual. That wait is intentional. It is not a broken button. If the wait is long, use the contact page rather than opening a second account with a different email and a second half-imported file.'],
    ['Free is a limit, not a different app',
      'When the trial ends you can stay on Free inside the limits shown in the product, or move to Paid. The ledger you built does not evaporate because the trial clock did. Read the current limit list in the app for counts such as alerts. A guide written today should not be your only copy of a number that the plan screen can change.',
      'Limits are there so the free service stays sustainable. They are not a judgment of your portfolio. If you hit a cap, export the book, decide whether Paid is worth it for the way you invest, and do not create extra accounts to dodge the cap. Split accounts are how reconciliations go wrong.',
      'Google Drive is optional on the account you connect. It is not a hidden Paid-only file format. What Paid changes is the set of limits, not the fact that the snapshot lives in your Drive.'],
    ['How to judge the product during the trial',
      'Import or type a month of trades you can still check, including fees and one dividend if you had one. Compare open quantities to the broker. Compare cash to deposits, withdrawals, and the trades. If those match, the tool fits. If they do not, you have found the bug or the missing entry while support can still help.',
      'Try one chart, one alert, and one export. You are checking the jobs you will actually do on a Sunday night, not every screen. A feature you do not understand yet is not a reason to pay, and it is not a reason to dismiss the ledger if the ledger is right.',
      'Write down the mismatch if you find one, with the symbol and the date. “Numbers are wrong” is hard to fix. “The 12 March buy of 200 shares is missing the commission” is not.'],
    ['Paying, and changing your mind',
      'Paid plans are optional. If you pay, keep the receipt and the email, and make sure the account email matches the one you use to sign in. The wrong email is the usual reason a person cannot see the plan they bought.',
      'You can export before you cancel, before you delete the account, and before you disconnect Drive. Do that export even if you intend to stay. A local file with a date in the name is the copy that does not depend on a login.',
      'Refunds, durations, and prices are whatever the plan screen and the terms say at the time you pay. This article does not freeze a price. If a page and the screen disagree, the screen and the terms you accepted are the ones to follow, and you can ask support to explain the difference.'],
    ['What neither plan will do',
      'Free and Paid both refuse the same jobs, because they are not the product. The app will not place a PSX order, will not file a tax return, and will not tell you that a share is halal. Paying does not buy a different set of facts. It buys fewer limits on the same tools.',
      'Market data can be wrong on either plan. A subscription is not a warranty on a price. Check the broker before you trade, and check the contract note after you do.',
      'If you only need the written guides, they stay public. You do not need a trial to read how FIFO, dividends, or CGT records work. The trial is for the ledger.'],
  ],

  'importing-broker-trades': [
    ['Decide the source of truth before the first row',
      'An import is a draft of history, not a new history. The contract note and the period statement remain the originals. Your job during import is to land each fill once, with the right symbol, side, date, quantity, price, and fees. Anything the file does not contain, you add by hand from the PDF.',
      'Pick one file as the master for a date range. Importing the same month from a CSV and again from a screenshot will double the trades. If you must try a second method, do it in an empty portfolio and compare counts before you merge.',
      'Write down the date format of the file. A statement that prints 04/05/2026 may mean 4 May or 5 April. The wrong reading moves the trade across a dividend or a tax year. Open one row you remember and confirm the month before you accept the batch.'],
    ['Columns that have to be right',
      'Symbol, buy or sell, quantity, price, and date are the minimum. Fees belong in the same row or in a fee column you understand. A row without fees is a cheaper trade than the one you actually did, and every later gain is overstated by that amount.',
      'Deposits and withdrawals are not trades. If the file mixes cash movements with buys, map them to the right type. A deposit marked as a buy will create a fake holding. A withdrawal marked as a sell will close shares you still own.',
      'Reject rows you do not understand. A blank symbol, a zero quantity, or a price that is a hundred times the neighbor is a parse error. Skipping it and entering it by hand is faster than debugging it next year.'],
    ['Gemini scans and Gmail attachments',
      'A scan of a PDF or a photo is a reading, and readings make mistakes. Digits swap, a sell becomes a buy, and a total line gets imported as a trade. The review screen exists so you can catch that before it hits the ledger. Accept rows one by one if the statement is messy. Accept a batch only when you have checked the count and the first and last trades.',
      'Gmail import, if you turn it on, lists messages you search for and downloads the attachment you select. It does not read your whole inbox for fun, and it does not send mail. You can leave it disconnected and still type trades or upload a file from the broker’s site.',
      'Do not scan a statement that includes account numbers you would not want in an AI request, if that bothers you. Manual entry and CSV exist for that reason. The privacy page describes what an optional scan sends.'],
    ['After the import, before you trust the totals',
      'Count the buys and the sells against the statement. Then match the open quantity of your largest holding. Then match cash, remembering that transfers between your own portfolios are not deposits. Those three checks catch the ugly errors. The pretty errors, a fee in the wrong column, show up when a single trade’s cost does not match the contract note.',
      'Same-day trades need a second look. A sell that the file lists above the buy of the same shares can look like an oversell if the importer keeps file order and forgets that the purchase happened first. The app’s cash and lot logic applies the day’s buys before the day’s sells. Your review should still confirm both rows exist.',
      'Corporate actions will not be in a trade blotter. Bonus shares and rights issues arrive as a separate notice. Add them after the import, or the quantity will be short and you will “fix” it with a fake buy at the wrong price.'],
    ['A repeatable monthly import',
      'Do a small import on a schedule instead of a heroic annual one. Monthly, you still remember the odd trade. Annually, you remember nothing and the file has four formats because the broker changed the export.',
      'Keep the source file next to the export from PSX Tracker, with the month in the filename. If a later import goes wrong, you can restore the backup from before the import and try again. The Drive guide explains how not to restore over the only good copy.',
      'When the open quantities match the broker for three months running, you have a ledger. Until then you have a project. Treat the dashboard numbers as provisional while the project is open, and do not make a tax estimate from a book you have not reconciled.'],
  ],

  'multi-portfolio-stocks-vs-funds': [
    ['Two books, one investor',
      'Shares and fund units answer to different statements. The broker and CDC tell you about shares. The asset manager tells you about units. Putting both in one list feels tidy and makes every total harder to audit, because a “quantity” of 500 might be shares or units and a “price” might be a trade or a NAV.',
      'PSX Tracker keeps a stock portfolio and a fund portfolio so the calculations stay in their own language. FIFO lots, board prices, and contract notes stay with the shares. Subscriptions, redemptions, and NAVs stay with the funds. A combined screen can add the market values afterward for a net-worth glance.',
      'You can also keep more than one stock portfolio: a spouse’s holdings, a longer-term book, a smaller experimental book. Label them by the statement you will reconcile them to. “Growth” is a mood. “MCB account ending 1842” is a label you can check.'],
    ['Cash is not a single pocket',
      'Money at the broker is not money at the asset manager, and neither is money in your bank. The stock portfolio’s cash should explain the broker wallet: deposits, withdrawals, buys, sells, dividends, and fees. The fund portfolio should explain payments to and from the manager. Transferring a figure from one book to the other without an actual bank movement will make one side negative and the other magical.',
      'A transfer of shares between two of your stock portfolios is not income and not a deposit. The shares leave one book at their cost and arrive in the other at that same cost. Recording the arrival at the market price creates a gain on a day you did not sell.',
      'If you fund a fund subscription by withdrawing from the broker, record both events. The withdrawal is cash leaving the broker. The subscription is units arriving at the manager. Skipping either one makes net invested wrong, which makes every return percentage wrong.'],
    ['Combined view without a combined mess',
      'The useful combined number is market value plus the cash that belongs to you, across books. It is a snapshot. It is not a single FIFO stack and it is not a single tax figure. Taxes on a share sale and taxes on a fund redemption follow different statements. Add the values. Do not add the tax stories.',
      'Performance against the KSE-100 should use the share book, or a combined book you understand, and should say which. An income fund will not track the index, and it should not be blamed for that in a chart labeled as equity performance.',
      'Dividends from shares and distributions from funds can both be income and still should stay attached to the book that received them. Otherwise a later reconcile cannot tell which statement to open.'],
    ['Day-to-day switching',
      'Work in the book that matches the statement in front of you. If the broker PDF is open, you are in the stock portfolio. If the fund allocation email is open, you are in the fund portfolio. Switching first prevents the classic mistake of typing a fund subscription as a share buy of a made-up symbol.',
      'The default broker on a stock portfolio is a convenience for new trades. It should be the broker on the statement. Trades from a second broker need the broker field changed, or they will reconcile to the wrong login.',
      'Drive backup stores the set of portfolios, not one of them. A restore brings the set back. Check both books after a restore, not only the one you use daily. The quiet book is the one that gets stale.'],
    ['When you should not merge',
      'Do not merge a joint account into a personal one to see a bigger chart. Beneficial ownership matters for tax and for the argument you will have later. Keep the books apart and look at a combined view if you want the picture.',
      'Do not merge history from before a corporate action with a fresh import that already includes the new shares, unless you have removed the overlap. Two sources for one fill is the most common double count.',
      'If a merge is truly what you want, export both books, keep the files, and reconcile the result to both statements in the same sitting. A merge without that hour is how cash goes negative and stays there.'],
  ],

  'watchlists-and-alerts': [
    ['A watchlist is a research queue',
      'The list is names you might study or already follow, not names you own. Keeping them out of the holdings list protects your performance figures from imaginary positions. If you want to remember a price you noticed, the watchlist is the right drawer. The holdings drawer is only for shares that settled.',
      'Group by the question you are asking. A list of “dividend names I might add” and a list of “reports due this month” will stay shorter than one list of everything you have ever typed. A long list becomes wallpaper. You stop seeing the new line.',
      'Sectors on the list follow the names the market publishes, mapped onto a stable label so “oil and gas” does not appear as three spellings. The label is a filing aid. It is not a rating and it is not a Shariah screen.'],
    ['What an alert can and cannot do',
      'An alert watches a price you set and tells you when the published quote has crossed it, if notifications are allowed and the plan limit has room. It does not place an order. It does not know why the price moved. It does not wait for the volume you wanted or the news you have not read.',
      'Set the level from a decision you already made: “I will re-read the filing if it trades below this” or “I will review the size if it reaches the price I said was expensive.” An alert at a random round number trains you to tap notifications and do nothing.',
      'The condition has to be on the possible side of the current price. An “alert me when it falls below” a number that is already below the price would have fired already. The app rejects impossible directions so you do not think you are protected by an alert that can never trigger.'],
    ['Limits, permissions, and missed alerts',
      'Browser notifications need permission, and they need a browser that is willing to deliver them. A phone in focus mode will swallow the ping. Treat an alert as a convenience, not as a stop-loss that exists at the exchange. If you need an order to exist, enter it at the broker.',
      'Free and Paid plans cap how many symbols and how many levels you can watch. The cap is printed in the product. If you need more names than the cap, you are using alerts as a second watchlist. Use the watchlist for the long list and alerts for the few prices that change an action.',
      'A missed alert is not proof the price never traded there. Data can be delayed or absent. If the level mattered, look at the broker’s chart for that day before you assume the condition is still ahead of you.'],
    ['From the list to a real holding',
      'When you do buy, record the fill in the portfolio. The watchlist will not grow a quantity by itself, and it should not. Leaving the name on the watchlist after you own it is fine if you still want the alerts. The holding and the watch are different records.',
      'If you sell out, decide whether the alert still means something. An old “tell me above 200” on a name you no longer own is clutter, and on a capped plan it occupies a slot you might want for a name you hold.',
      'Delete with the same care you add. Removing a symbol from a watchlist does not sell it. Removing it from holdings does not cancel a broker order. Each list talks to a different system.'],
    ['Research hygiene',
      'Open the company page and the latest filing before you add a second alert. Two alerts on a name you cannot describe is how lists replace thinking. One sentence in your own words — what it sells, why the price level matters — is enough to keep the list honest.',
      'Do not paste a guru’s thirty tickers in one sitting. You cannot follow thirty stories. Pick the few you will actually read this month, and let the rest wait.',
      'Nothing on the watchlist is a recommendation from the app. You typed the symbols. The app fetched quotes and, if you asked, watched a level.'],
  ],

  'psx-portfolio-export-reconcile': [
    ['Why export if the screen already looks right',
      'The screen is a view. The export is a file you can diff against a statement without the app in the way. It is also the copy that survives a login problem, a phone replacement, or a restore you regret. Export on a schedule, name the file with the date, and store it next to the broker PDF for the same date.',
      'Reconcile means proving that three things match: quantities, cash, and the corporate actions you were party to. A match on quantity with a wrong cost is only a partial match. You will feel it later, when a sale’s gain looks nothing like the contract note.',
      'Do the work when you are not in a hurry to file or to pay someone. A calm hour finds the duplicated import. A panicked hour “fixes” it with an adjusting entry you will not understand in June.'],
    ['Quantities first',
      'For each symbol, write the broker or CDC quantity and the tracker quantity. Differences come from a missing buy, a duplicated sell, a bonus you did not record, or a transfer between portfolios that only one side received. Fix the event. Do not type a dummy trade at a made-up price to force the number.',
      'Funds get the same treatment against the asset-manager statement. Units, not rupees, are the first check. Rupees move every time NAV moves. Units move only when you transact or when the fund issues a corporate action.',
      'If a symbol exists in the tracker and not at the broker, you may have typed a buy that never filled, or you may be looking at the wrong broker’s login. The broker field on the trade is the clue.'],
    ['Cash second',
      'List deposits, withdrawals, buys, sells, dividends, and fees. Buys spend cash. Sells add cash only for the quantity you actually held. A sell of shares you did not own should not increase cash, because the proceeds were not yours. Dividends add the net cash and record the tax separately. Transfers of shares between your own books do not move cash at all.',
      'A negative cash balance is a signal, not a mood. It means the cash events you recorded cannot fund the purchases you recorded. The usual causes are a missing deposit, a buy entered twice, a dividend never entered, or a transfer treated as a withdrawal. Find which one. The identity is boring and reliable: if the events are complete, cash stops being a mystery.',
      'Broker cash and bank cash are different. Do not expect the tracker’s broker cash to equal your bank account. Expect it to equal the broker’s client-wallet statement.'],
    ['Costs and corporate actions third',
      'Pick five trades, including one old and one recent, and match price, quantity, and fees to the contract notes. Fees are where silent drift lives. A missing commission on every buy makes you look richer than you are.',
      'Then walk the year’s announcements for names you held: dividends, bonuses, rights, splits, face-value changes. Tick each one as recorded or as not applicable because you bought later. Face value matters when a dividend is declared as a percentage. A change in face value that you ignore will scale that dividend wrong.',
      'Average cost on the broker screen and FIFO cost in the tracker are allowed to disagree. They are different questions. Reconcile both to the lots, not to each other. The FIFO guide shows a small numerical example of that disagreement.'],
    ['Close the loop',
      'When quantities, cash, and the sample of contract notes match, write the date on the export. That file is a known-good point. A later import can be compared with it. If the later import is wrong, restore to the known-good file instead of editing blindly. Keep at least two of those dated files. A single export that you overwrite every Sunday is not a history.',
      'If they do not match and you cannot see why, stop adding trades. Export the broken book anyway, so you have it, and ask for help with a specific symbol and date. Support can think about a missing lot. Support cannot think about “it’s all off.” A named symbol, a date, and the two quantities is enough to start.',
      'Reconciliation is the product working. The dashboard is just the dashboard. Trust it after the statement agrees, and not before.'],
  ],

  'understanding-unrealized-vs-realized': [
    ['Two questions, two numbers',
      'Unrealized profit asks what the shares or units you still hold are worth against what they cost, at today’s price or NAV. It moves when the market moves, and it is not cash. You cannot spend it, and you have not paid tax on it, because you have not disposed of the position.',
      'Realized profit asks what happened on the sales you already made. Proceeds minus the cost of the lots those sales closed, minus the selling costs you include, is the gain you locked in. It does not change because the price changed tomorrow. Tomorrow is a new day for the shares you still have, not for the shares you sold.',
      'Putting the two numbers in one pot produces a figure with no verb. “I made 50,000” might mean the screen is green or it might mean you sold. The dashboard shows them separately so you can say which one you mean.'],
    ['How a sale moves the number from one column to the other',
      'Before the sale, the position’s gain is unrealized. When you sell part of it, the lots you closed leave the open book and their gain becomes realized. The shares you kept stay unrealized and keep their own cost. FIFO decides which lots left. Average cost would move a different gain into the realized column from the same sell order.',
      'A sale below cost realizes a loss. That loss is real in the personal ledger even if you do not enjoy looking at it. Hiding it inside a blended average of what you still hold makes the remaining position look worse and the past look cleaner than it was. Keep the loss on the sale.',
      'Fees follow the event. Buy fees sit in the cost of the open lot, so they reduce unrealized profit. Sell fees reduce the proceeds, so they reduce realized profit. Dropping fees from both makes both numbers optimistic.'],
    ['Cash, income, and transfers are none of the above',
      'A dividend is not unrealized and it is not a capital gain. It is income and, when it arrives, cash. A deposit is not a gain. A withdrawal is not a loss. A transfer of shares to another of your portfolios is not a sale. If any of those land in the realized column, the column stops meaning “I sold something.”',
      'Day-to-day P&L is a third idea again: how the market value changed since the previous close, on the shares you held. It is not the unrealized total, which measures you against your cost, and it is not the realized total, which measures closed trades. A green day can happen while you are still underwater versus cost. A red day can happen while your closed trades for the year are ahead.',
      'Net worth is market value plus cash. It includes unrealized gains because they are inside the market value. It does not add them a second time. If a screen ever seems to count the same profit twice, you are adding a total that already includes it.'],
    ['Why the broker’s average and your realized figure disagree',
      'Brokers often show one average buy price for the open position. That average is a convenient summary of what you still hold. It does not identify which lots a partial sale closed. Your realized gain can therefore differ from “average times quantity” and both screens can be internally consistent. The contract note plus the lot list is how you see which story you are in.',
      'Tax follows the disposal rules for the year, not the color of the unrealized number. You generally do not file the unrealized figure. You file the disposals, and only under the rules that apply to you. The CGT guide stays at that level on purpose and does not invent a rate.',
      'Fund redemptions realize a result on units. The manager’s statement may already net a tax. Read whether the figure you are copying is before that tax or after it, and do not subtract the tax again.'],
    ['Use the split when you review the month',
      'Once a month, read one sentence for realized and one for unrealized. Realized: which sales did I make, and do they match the contract notes? Unrealized: which open positions are doing the work, and do I still want them at this size? Mixing the sentences leads to selling a winner to “lock” a feeling, or to ignoring a real loss because the open book is green.',
      'If realized is a large loss and cash is also wrong, reconcile before you draw a lesson about your skill. A duplicated sell can manufacture a loss. A missing deposit can manufacture despair. The numbers are allowed to teach you only after they match the statements.',
      'PSX Tracker keeps the split so the lesson, when you are ready for it, is about your decisions and not about a blended blob. The tool does not grade the decisions.'],
  ],

  'psx-with-limited-capital': [
    ['Small accounts feel costs first',
      'A commission that looks tiny next to a large trade is a real slice of a small one. Before you buy, run the trade-cost calculator with the rate on your own fee card and the amount you will actually spend. If the charges are a painful share of the order, the order is too small for that broker’s schedule, or the habit of trading often is too expensive for the account.',
      'Minimum amounts, if the broker or a fund has them, are part of the same arithmetic. An open-end fund with a high minimum can be a worse fit for a tiny monthly saving than a single listed share, or the other way around. Compare the real minimum and the real charges, not the slogan.',
      'None of this says you must wait until you are rich. It says the first design problem is costs and the second is concentration. Solve those on paper before you solve them with a tip.'],
    ['One share is a portfolio, and that is the risk',
      'With little money you may only afford one name. That is an honest constraint. It means your result is that company’s result, not “the market.” A bad quarter, a halted plant, or a dividend cut lands entirely on you. Size the position as if that can happen, because it can.',
      'Adding a second name before you understand the first one does not create diversification. It creates two stories you are not reading. One understood holding beats five forgotten ones. When the account grows, add the second name on purpose, from the research checklist, not from a list of last week’s winners.',
      'Funds exist partly so a small saver can own a basket. The basket has a fee every year, and the units have their own statement. For some people that trade is better than one share. For others the annual fee is the expensive part. Read the offering document’s charges and decide with the numbers, not with a stranger’s rule of thumb.'],
    ['Cash you might need is not capital',
      'Money for rent, fees, or a medical bill is not investable just because the broker account is open. A forced sale in a bad week is how small accounts shrink. Decide the amount you can leave alone for years, and leave the rest in the bank. The tracker should show a deposit of only the amount you truly moved.',
      'Borrowed money magnifies the same problem. A small account that is also a loan can be wiped out by an ordinary move. This guide will not dress leverage up as a strategy for beginners.',
      'Write the number down. “I am investing this much, and I will add this much a month if the cash is there.” A written number stops a green day from pulling next month’s rent into a market order.'],
    ['Process that fits an hour a month',
      'You do not need a terminal and a dozen indicators. You need the contract note saved, the trade entered, and a quarterly look at whether you still understand the company. The charts and the filings are there when you want them. They are not homework assigned by the app.',
      'Automating the record is the part worth automating. Remembering to reconcile is the part you do yourself. Once a month, match quantity to the broker. That single habit prevents the small account’s usual failure mode: a year of trades that nobody, including you, can explain.',
      'If you miss a month, resume. Do not punish the gap by overtrading. Enter the missing fills from the statements and continue the plan you wrote.'],
    ['What not to expect',
      'A small account will not produce a salary. Anyone who shows you a screenshot where it did is selling you something. Returns are uneven, costs are certain, and a single name can go nowhere for a long time.',
      'The point of starting small is to learn the machinery with money you can afford to see fluctuate: the broker, the contract note, the dividend, the tax document, the feeling of a red week. The tracker’s job is to make that lesson visible. It is not to turn the lesson into a promise.',
      'When the account is larger, the same machinery still applies. You will be glad you learned it when the numbers were boring.'],
  ],

  'realistic-psx-returns': [
    ['Where a return can come from',
      'You are paid, if you are paid, in two ways. The company sends a dividend, or the price you can sell at is different from the price you paid. Both can be negative in the sense that matters: the dividend can be cut, and the price can be lower. Fees and taxes sit on top and make the amount you keep smaller than the headline move.',
      'The index is a basket with rules, weighted toward large companies, rebalanced on a published method. Your portfolio is whatever you bought. It can beat the index by luck or skill, and it can lag the index while the index itself is down. Comparing them is useful. Confusing them is how people say “the market did well” in a year their own book did not.',
      'A fund’s return is the change in NAV plus distributions, after the fees the document describes. It is not the KSE-100’s return, even for an equity fund, because the holdings and the fees differ.'],
    ['Past numbers are a record, not a forecast',
      'A decade in which an index rose a lot does not owe you the same decade again. Inflation, the currency, political news, and a handful of large stocks can dominate a period. Remove one or two names and the story of “the market” often changes. That is a reason to read the constituents, not a reason to memorize a percentage from a thumbnail.',
      'Company history is the same shape. A fertilizer producer’s golden years are not a bond. A bank’s low provisions in a calm year are not a promise about the next credit cycle. The research guides on banks and cement are checklists of what to read, not predictions.',
      'Your own past return, once the ledger is reconciled, is the only personal number. It includes your costs, your timing, and your mistakes. It is allowed to be worse than the index. That fact is information. It is not an insult and it is not a reason to double the next trade.'],
    ['Costs and taxes are part of the result',
      'Commission, taxes on commission, and CDC charges come off whether the trade worked or not. A strategy that trades every day pays them every day. A strategy that buys and holds pays them less often and still pays a spread and a tax when it eventually sells.',
      'Dividend withholding means the cash you receive is less than the dividend the company declared. Record both, or your yield will look higher than the money that arrived. Capital gains tax, when it applies, comes off realized gains. Unrealized gains have not met that tax yet. The CGT guide explains the record you need without inventing the rate.',
      'Fund management fees are easy to ignore because they are taken inside the NAV. They are still your cost. The factsheet states them. Subtracting them again on top of the NAV change would count them twice, so read whether the NAV you see is already net.'],
    ['Risk is the chance you needed the money',
      'A return that arrived after a 40 percent decline was not “about 15 percent a year” to the person who sold at the bottom to pay a bill. The path matters. If you cannot leave the money alone, you do not have the return the brochure averaged. You have the return up to the day you were forced out.',
      'Concentration makes the path rougher. One stock, one sector, or one fund category is a bet that that story stays healthy. Diversification across names you understand reduces the chance that one story ends you. Diversification across names you do not understand reduces nothing you can act on.',
      'Leverage and borrowed confidence from a group chat shorten the path further. A realistic plan states the amount, the horizon, and the reason you would sell. “It was going up” is not a reason you can reuse.'],
    ['How to use the tracker in this light',
      'Let the app show your return, the index, and the cash flows separately. A positive day on the index and a negative day on your book can both be true. The chart of daily moves is there so you can see the path. The total-return figure is there so you can see the destination so far, including dividends and costs you recorded.',
      'If the figure surprises you, reconcile before you change your life. A missing dividend understates you. A duplicated buy overstates cost and understates the return. The surprise might be the data.',
      'No screen on this site, and no paragraph in this guide, is a forecast or a suitable-for-you recommendation. The realistic expectation is modest, uneven, and entirely dependent on what you bought and what you paid away.'],
  ],

  'kmi-and-shariah-screening': [
    ['What gets published',
      'A KMI-style screen publishes two things you should insist on seeing together: the methodology, and the list of constituents produced by that methodology on a date. The methodology says which businesses are excluded and which financial ratios are tested, against which totals, with which cutoffs. The list is the output. Either piece alone is an advertisement.',
      'The publisher can revise the method. A cutoff you memorized may be the previous notice. Read the notice that matches the list you are using, and keep the PDF. A blog summary is not the notice.',
      'Indexes also have weight rules, caps, and rebalance dates. Those affect the index level. They are a separate document from the question of whether a given company passed the screen.'],
    ['How to read a constituent list',
      'Find the company, the symbol, and the effective date. Check whether the list you have is the index, a watchlist for possible inclusion, or a list of deletions. People circulate screenshots that mix those categories.',
      'A company on the list has passed the published tests for that period. It has not been declared suitable for you. Your financing, your broker arrangement, and the scholar you follow can still put the share outside your own rule. A company off the list has failed the published tests or was not eligible. It is not automatically forbidden by every method in the world. It failed this one.',
      'Additions and deletions are the useful part of the announcement. A deletion is a prompt to re-read the accounts, not an instruction from this website to sell. A purchase or a sale is your decision, made with the notice in front of you.'],
    ['Ratios without the statements are rumors',
      'If you want to understand a borderline name, open the annual or quarterly accounts and identify the lines the methodology names. Debt, interest income, and non-compliant income are defined in the method. They are not “whatever a forum called debt.” Write the figure, the page, and the period.',
      'Interim accounts can move a ratio across a cutoff before the next index review. The index will not update on the morning the accounts are filed. If your rule is “I follow the index,” wait for the index. If your rule is “I apply the method myself,” do the arithmetic and accept that you may disagree with the index until it rebalances.',
      'Do not let a portfolio app’s sector label stand in for this work. Sector labels group businesses for browsing. They are not the screen.'],
    ['Funds that say they follow a screen',
      'An Islamic equity fund’s offering document should say which screen it uses and what it does when a holding falls outside the screen. Read that policy. The fund’s name is not the policy. The factsheet’s top holdings are a snapshot, not the policy either.',
      'You still own units of the fund, not a personal copy of the index. The manager’s tracking difference, cash, and fees mean your units are not identical to the index level. Judge the fund by its document and its reports.',
      'A conventional equity fund can hold many of the same companies without applying the screen. Do not infer a screen from a familiar ticker in the top-ten list.'],
    ['Keep the decision dated',
      'When you buy or decide not to, note the list date and the document you relied on. Six months later the list may have changed and you will want to know what you knew then. The tracker’s notes and the trade date are a reasonable place. The ruling, if you sought one, lives with you, not in the app.',
      'Re-read on a schedule you can keep, perhaps when each new list is published, rather than every red day. A price move is not a change in the company’s debt ratio. Save the PDF of the list next to the trade note so the date and the methodology version stay attached to the decision.',
      'PSX Tracker will not stamp a ticker as compliant. Use the publisher methodology and, where you need it, a qualified scholar. This guide only tells you how to hold those documents up to the light. If a later list removes a holding, the trade date in your ledger shows that you bought it while it was still on the earlier list.'],
  ],

  'stock-factors-investors-watch': [
    ['A factor is a question, not a score',
      'People say “quality” and “value” as if they were buttons. Each one is a pile of questions. Quality might mean the business earns high returns on the capital it uses, converts those earnings into cash, and does not depend on a single customer or a single raw material. Value might mean the price you pay is modest against those earnings, against the assets, or against the dividends. Neither question is answered by one ratio on one year.',
      'A screen that sorts the whole market by one number will hand you a list of accounting accidents. A one-off gain, a change in depreciation, or a year of unusually low tax can make a company look cheap or profitable. Read the note under the number before you read the number.',
      'This guide walks through the questions Pakistani investors commonly ask. It does not produce a ranking, and the app’s research pages are not a buy list when they show the same figures.'],
    ['The business and its revenue',
      'Start with what is sold, to whom, and what it costs to deliver. A cement plant, a bank, and a software exporter do not share a useful “average margin.” Compare a company with its own history and with peers that do the same thing. The cement and bank guides on this site are examples of that peer reading.',
      'Concentration is a factor even when it is not in a screener. One product, one buyer, one concession, or one regulated price means the future is a single decision someone else makes. You can still own it. You should know you own that decision.',
      'Growth is only pleasant when the company can fund it. Growth funded by endless new shares or by debt that the cash flow cannot service is a different factor, leverage, wearing a cheerful name.'],
    ['Profit, cash, and the gap between them',
      'Profit is an opinion the accounts assemble under a standard. Cash from operations is closer to the bank. A company that reports rising profit and weak operating cash, year after year, is asking you to believe in receivables, capitalization policies, or both. Read the cash-flow statement, not only the earnings line the ratio used.',
      'Margins tell you what is left after the direct costs. They move when input prices move. For a manufacturer, energy and raw materials can dominate. For a bank, the interesting “margin” is the net interest margin, which is a different construction entirely. Do not drop both into one column and sort.',
      'One excellent year is a story. Five ordinary years are a pattern. Factors that depend on a single year will rank the lucky and the aggressive above the steady. Look at the run of years in the financials panel or, better, in the annual reports.'],
    ['Leverage and dilution',
      'Debt matters because the lender gets paid before you do. The useful questions are how much, at what cost, secured against what, and what happens if the main profit source dips. A low debt number in a business that does not need debt is different from a low debt number in a business that usually carries a lot and happens to be between projects.',
      'New shares matter because your fraction of the business shrinks. A rising profit shared with a much larger number of shares can leave earnings per share flat. Read the share count. Bonus issues and splits change the count without new money. Rights issues change the count and ask you for money. Record which one happened so your per-share history stays honest.',
      'Related-party loans and guarantees often sit in the notes, not in the headline ratio. If the company is lending to its sponsors or borrowing from them, that is part of the factor, not a footnote you skip.'],
    ['Valuation is the price of the other factors',
      'A fine business at a reckless price can be a poor investment. A mediocre business at a distressed price can be a fine one, or a trap. The P/E guide covers one common yardstick and the ways it misleads. Price to book, dividend yield, and enterprise measures against cash flow are other yardsticks. Use more than one, and use them against peers.',
      'The price half of every valuation ratio is today’s market. It changes while you are reading. The earnings half changes when the next accounts arrive. A ratio without a date is not a fact you can file.',
      'No combination of factors removes the chance of being wrong. The point of writing them down is to know why you bought and what would make you revisit. The tracker can hold the position and the notes. It cannot hold the conviction for you.'],
  ],

  'pe-ratio-for-psx-stocks': [
    ['The ratio in one sentence',
      'Price to earnings divides a share price by an earnings-per-share figure. It answers “how many rupees of price am I paying for one rupee of the earnings someone measured?” It does not answer whether the earnings will continue, whether the accounts are aggressive, or whether a peer’s earnings were measured the same way.',
      'You can compute it with last year’s reported earnings, with the last four quarters, or with a forecast. Those are three different ratios. A conversation that does not say which one is a conversation about different numbers. Prefer the one you can recompute from the published accounts, and label a forecast as a forecast.',
      'Earnings per share already spreads profit across the share count. If the company issued shares halfway through the year, the count used in the accounts matters. Read which weighted average they used instead of dividing by today’s share count and calling it close enough.'],
    ['Why two screens disagree',
      'One source may exclude a one-off gain, a surplus on sale of a plant, or a tax reversal. Another may leave it in. The lower P/E is then an accounting choice, not a cheaper stock. Open the profit note and see how large the unusual item was relative to the profit you are about to divide into.',
      'One source may use the price at the last close. Another may use a price from a different day, or a price adjusted for a bonus the first source has not adjusted. After a bonus or a split, either both the price and the historical earnings per share move together, or neither does. Adjusting only one side invents a cheap or expensive stock.',
      'A loss makes the ratio meaningless or negative. Sorting those names into a “cheap” bucket is a bug in the screener. A tiny profit makes the ratio enormous. Neither extreme is a valuation. It is a sign to read the year instead of the quotient.'],
    ['Peers, or it is just a number',
      'A P/E of 8 on a cement company and a P/E of 8 on a software exporter are not the same claim. Compare inside an industry, and even then compare the growth, the debt, and the share of earnings that becomes cash. The factors guide is the wider checklist. This page is only the yardstick.',
      'Banks are the classic trap. Earnings can look high because provisions were low, and the more relevant comparison is often price against book value and the return the bank earns on that book. The bank guide covers that. Do not throw bank P/Es into a list with industrial companies and call the sort a research process.',
      'A company that always looks “cheap” on earnings and never converts them to dividends or to a stronger balance sheet may be cheap for a reason you can find in the notes: a regulator, a circular-debt receivable, a sponsor, a plant that needs cash.'],
    ['What to write down when you use one',
      'Record the price, the date of the price, the period of the earnings, the earnings figure, and the source. “P/E 7” is not reproducible. “Close on this date, earnings for the year ended, page of the annual report” is reproducible. Your future self can then see whether the cheapness was real.',
      'Recompute after the next results. The price will have moved and the earnings will have moved. A thesis that depended on the old ratio needs the new ratio, not loyalty to the old screenshot.',
      'If you cannot explain the earnings in a sentence — what the company sold, and what was unusual — do not use the ratio yet. You would be dividing a price by a number you do not understand, which feels like analysis and is not.'],
    ['Where this sits in the tracker',
      'Research pages may show a P/E the data vendor computed. Treat it as a clue that points you at the accounts, not as a conclusion. If it disagrees with your arithmetic, your arithmetic from the primary document wins, or you find the definition you missed. Either way you learned something.',
      'The ratio has no place in your cost basis. You do not buy a P/E. You buy shares at a price, plus fees, on a date. The ledger records that. The P/E is a note about whether the price seemed reasonable at the time.',
      'Nothing here says a low ratio is a buy or a high ratio is a sell. Some excellent businesses deserve a higher multiple, and some low multiples are a warning. The accounts tell you which file you are holding.'],
  ],

  'graham-style-margin-of-safety': [
    ['The idea, without the costume',
      'Margin of safety is the gap between what you think a business is worth and the price the market asks. You want the price to be lower, by enough that you can be somewhat wrong and still not be ruined. Benjamin Graham wrote about this as a discipline of conservatism. This page is a plain explanation of the discipline. It is not a complete copying of his books, and it is not a formula that prints a fair value.',
      'The gap exists only if your estimate of value is independent of the price. If you take the price, multiply it by a story, and call the result value, there is no gap. There is a circle. Start from the business: what it earns, what it owns, what it owes, and what a cautious person would believe those figures will do.',
      'A large gap does not make you safe. It makes the odds less brutal if your estimate was nearly right. If your estimate was fantasy, the gap was fantasy too.'],
    ['Value is a range',
      'Use more than one blunt measure. What do the assets look like after a haircut to receivables and inventory you would not want to collect yourself? What does a conservative multiple of average earnings say, using a run of years rather than the best year? What does the dividend stream look like if you refuse to assume it grows?',
      'Where those approaches cluster, you have a range. Where they scatter, you do not understand the business well enough to claim a value. The honest output is “I do not know,” which is a reason not to size a large position.',
      'Write the assumptions next to the range. A change in the sugar price, the policy rate, the gas tariff, or the tax rate can move the range by more than the margin you thought you had. If the thesis depends on a policy that can be revised in a budget speech, the margin needs to be wide or the position needs to be small.'],
    ['The market’s job is to offer a price, not to be right',
      'Prices move because other people are forced to, bored, frightened, or excited. You do not need a theory of their mood. You need a price that is attractive against the range you wrote down when you were calm. If the price is not attractive, you do nothing. Doing nothing is the usual correct action.',
      'A falling price is not automatically a larger margin of safety. The value may have fallen with the price, because the business got worse. Re-read the latest accounts before you add. The phrase “it is cheaper now” skips that re-reading and has funded a lot of losses.',
      'A rising price can erase the margin while the business stays fine. That is a reason to be careful about adding, not automatically a reason to sell a business you still understand. Selling and buying have costs. The margin is a buying discipline first.'],
    ['Position size is part of the margin',
      'Being right and being wiped out can happen together if the position was so large that an ordinary error became a personal crisis. The margin of safety in the price does not replace a limit on how much of your savings one name can be. Decide the limit when you are calm.',
      'Averaging down is only coherent when the value is intact and the new price improves the gap. Averaging down because you cannot bear the red number is how a small mistake becomes the whole portfolio. The ledger will show the new, lower average. It will not show that you broke your limit. You have to write the limit somewhere you will see it.',
      'Diversification across a handful of understood businesses is another kind of margin: against the chance that one range was wrong. A long list of half-understood bargains is not that. It is a second job you will not do.'],
    ['How to keep the practice in the tracker',
      'You can note, in your own words, the range you estimated and the price you paid. Months later the unrealized figure tells you how the market moved, not whether your range was right. Revisit the range when new accounts come out. Update the note. Do not update the story to match whatever the price did.',
      'Nothing in PSX Tracker calculates intrinsic value. Be wary of any tool that offers a single precise fair-value number with false confidence. A range you built from the annual report, with the assumptions visible, is slower and better.',
      'This is not advice to buy cheap stocks, and it is not a claim that Graham’s older numerical rules still fit every Pakistani company. It is an invitation to pay less than a cautious estimate, on purpose, and to admit when you do not have one.'],
  ],

  'analyze-cement-stocks-psx': [
    ['What a cement company is',
      'A listed cement company quarries limestone, burns it into clinker, grinds cement, and sells bags and bulk into construction. The plant is heavy, local, and expensive. Once it exists, the cost of running it and the price of a bag decide the year. Demand follows construction: public projects, private housing, and, for some firms, exports of clinker or cement.',
      'Peers are other cement producers, not “industry” in the abstract. A company with a plant far from its customers pays more to move a heavy product. A company with a new line has capacity that helps only if the market can take the bags. Read the annual report’s description of plants and markets before you compare ratios.',
      'Several Pakistani groups also own businesses beside cement: power, autos, chemicals, overseas plants. The consolidated accounts mix those stories. The note on segment results is where you separate the cement from the rest. If you skip it, you will praise or blame the cement cycle for a profit that came from somewhere else.'],
    ['Dispatches, prices, and costs',
      'Monthly dispatch numbers, when the company or the industry association publishes them, tell you about volume. They do not tell you about the price per bag or the cost of coal, electricity, and freight. A record month of volume with a weak price and expensive coal can be a poor month of profit. Wait for the accounts to see the margin.',
      'Energy is the swing factor. Kilns burn fuel, and grinding and quarrying use power. A change in the fuel mix, the coal price, or the grid tariff moves the cost line faster than a slow change in demand. The director’s report often discusses this in plain language. Read it.',
      'Do not treat a dispatch headline as a reason to buy before the close. It is one input, it is public, and the price may already reflect it. Your job is to see whether the full picture — volume, price, cost, debt — still matches the reason you own the shares.'],
    ['Capacity and the new line',
      'A new line is a promise of volume and a certainty of debt or equity raised to build it. Until it runs reliably, the company has spent the money and has not received the bags. Read the project note: cost, financing, and expected timing. Slippage is normal. A thesis that needs the line to start in a particular quarter is a thesis that can be late.',
      'Extra capacity in the country can pressure prices even when one company’s plant is excellent. Cement is hard to differentiate. If many lines start together, the industry’s pricing can be worse even while your company’s volumes rise. That is a reason to know what peers are building, from their own reports, not only what your company is building.',
      'Exports add a second market and a second set of freight and currency questions. They are not automatically higher quality earnings. Read whether export margins look like local margins or like a way to keep kilns running.'],
    ['Debt, working capital, and the sponsor',
      'Cement expansion is often borrowed. The useful questions are the same as in any leveraged industrial: the amount, the currency, the rate, and the schedule, set against the cash the plants produce in a weak year rather than in the best year. A ratio that only looks comfortable in the best year is not comfortable.',
      'Receivables and stocks of clinker and spares tie up cash. A profit that does not arrive as cash will show up here and in the cash-flow statement. Use both.',
      'Group companies can buy, sell, and lend inside the family of firms. The related-party note is part of the analysis, not an appendix for specialists. You want to see whether the listed company is run for its own shareholders.'],
    ['A compact checklist before you size it',
      'In your own words, write what the company sells and where. Note the latest year’s dispatches if you have a primary figure, the gross margin, the debt, and one sentence on the project pipeline. Then look at the valuation against other cement producers, not against the whole market. The P/E guide explains the traps in that comparison.',
      'Record dividends separately from the price. Some cement names have paid regularly and some have not. The history is in the company notices. A yield you computed from a chat is not the history.',
      'This checklist is not a list of cement stocks to buy. Plants, quarries, and balance sheets differ, and they change. The annual report and the PSX filings are the documents. The tracker is where you record the shares if you decide to own them.'],
  ],

  'analyze-pakistani-banks-psx': [
    ['A bank’s product is a spread and a promise',
      'A commercial bank takes deposits, makes loans and investments, and earns the difference, minus credit losses and operating costs. That difference is not a factory’s gross margin. Comparing a bank’s “P/E” with a cement company’s P/E, as if they were the same kind of cheap, is a category error. Start with the banking figures.',
      'Islamic banks do the same economic job under contracts that are meant to avoid interest. Their reports use different words. The questions — quality of financing, funding stability, capital — still need answers. The halal guide explains why the word “Islamic” on a bank is the start of a reading, not the end of one.',
      'You are buying a leveraged institution. A bank’s equity is a thin layer under a large pool of other people’s money. Small changes in asset quality move the equity hard. That is the reason bank analysis starts with the loan book and the capital, not with the share-price chart.'],
    ['Deposits and funding',
      'Deposits are the raw material. Current and savings accounts are usually cheaper and stickier than borrowing in the wholesale market. A bank that funds itself expensively will look fine while rates cooperate and strained when they do not. The deposit note and the mix over several years tell you more than one quarter’s profit.',
      'Growth in deposits is only good when the bank can place the money in assets it understands. Deposit growth that races ahead of the bank’s ability to underwrite is how later losses get financed.',
      'Related-party deposits and deposits from government or other concentrated sources deserve a look. Cheap funding that can leave in a season is not the same as a wide branch base of small accounts.'],
    ['Net interest margin, or its Islamic analogue',
      'The margin measures what the bank earns on assets minus what it pays on funding, relative to the size of the book. It moves with the policy rate, the mix of deposits, and competition for loans. A wide margin in one year can be the rate cycle, not a permanent skill.',
      'Read the margin next to the fee income. Some banks earn a durable share from fees and services. Others lean entirely on the spread. The mix changes how painful a turn in rates will be.',
      'For an Islamic bank, read the profit-sharing and financing income the way you would read the margin: what was earned, on which book, and whether it is repeating. Do not force the conventional label onto a line that the report has defined differently. Use their definition, consistently, across years.'],
    ['Credit quality and capital',
      'Non-performing loans are the loans that have already gone bad under the regulator’s definition. Provisions are what the bank has set aside. The interesting question is whether the allowances cover the bad book, and whether the next year’s economy looks like the one in which this coverage was enough. A low NPL ratio after a calm period is not a law of nature.',
      'Capital adequacy is the buffer the regulator requires against losses. A bank can earn a high return on equity partly because it runs with less capital. That return is not free. It is the other side of a thinner buffer. Read the capital ratio beside the return, not instead of it.',
      'Price to book compares the market price with the accounting equity per share. A low multiple can mean the market doubts the book: the loans, the subsidiaries, the assets that have not been marked. A high multiple can mean the market believes the franchise earns more than the book suggests. Neither multiple is a conclusion until you have read the credit section.'],
    ['Using the reports with the tracker',
      'Once a year, when the annual accounts arrive, update a few lines in your own note: deposit growth, margin, NPL ratio, coverage, capital ratio, and price to book, each with the page they came from. You are building a personal time series the screener will not keep honest for you.',
      'Dividends from banks can be regular and can also be constrained by the regulator or by the need to keep capital. Record what was actually paid. Do not capitalize a hoped-for payout into a value estimate without saying you did that.',
      'Nothing on this page is a ranking of Pakistani banks or a suggestion to prefer one symbol. The reports are public, long, and enough. The app can hold the shares and the dividends after you decide. It cannot read the loan book for you.'],
  ],
};
