const disclaimer =
  'This guide is educational only. It is not investment, tax, legal or religious advice. Rules, fees and tax rates change — confirm details with your broker, SECP/PSX sources, FBR guidance and qualified advisors before you act.';

/**
 * Long-form Learn PSX articles. Section shape: [heading, ...blocks]
 * where each block is a paragraph string or a string[] bullet list.
 * @typedef {[string, ...(string|string[])[]]} GuideSection
 * @typedef {{ title: string, description: string, intro: string, blurb: string, sections: GuideSection[], related?: string[] }} GuidePage
 * @type {Record<string, GuidePage>}
 */
export const learnGuidePages = {
  'start-investing-on-psx': {
    title: 'How to start investing on the Pakistan Stock Exchange',
    blurb: 'Broker, KYC, funding, first buy — then keep a clean portfolio record.',
    description: 'Step-by-step guide to starting on PSX: choose a broker, complete KYC, fund your account, buy shares, and track your holdings.',
    intro: 'Short answer: to invest on the Pakistan Stock Exchange you open an account with a registered broker, finish KYC, deposit money, and place orders on their platform. Most of that can be done online in a few working days. This walkthrough explains each step in plain English — and why recording every trade matters once you begin.',
    sections: [
      ['What is the Pakistan Stock Exchange?',
        'The Pakistan Stock Exchange (PSX) is the country’s national stock market. Companies list shares there so investors can buy and sell ownership stakes during market hours.',
        'PSX is overseen by the Securities and Exchange Commission of Pakistan (SECP). Clearing and settlement involve institutions such as NCCPL, and shareholding is typically held electronically through the Central Depository Company (CDC) system rather than paper certificates.',
        'You do not walk onto a trading floor as a retail investor. You trade through a broker that is allowed to access the exchange on your behalf.'],
      ['Step 1 — Choose a broker',
        'A broker is the firm that opens your trading account, sends your orders to the market, and issues contract notes. Only brokers registered for PSX trading can do this legally for you.',
        'When you compare brokers, look past brand names and check the basics yourself on their current fee card and app store reviews:',
        ['Commission and other trading charges (these change — verify today’s schedule)', 'How easy the mobile or web app is for placing and reviewing orders', 'Deposit and withdrawal process for your bank', 'Quality of statements and exports (CSV/PDF help portfolio tracking)', 'Customer support in a language you are comfortable with'],
        'You can confirm registered brokers via official PSX / SECP channels. Do not send money to anyone who only chats on WhatsApp and asks you to “invest with them” outside a licensed broker account.'],
      ['Step 2 — Open your account and CDC sub-account',
        'After you pick a broker, you complete their account opening and KYC. In practice your broker also arranges a CDC sub-account — the electronic place your shares are held. You usually do not need to visit a CDC office yourself.',
        'Brokers commonly ask for items such as:',
        ['CNIC (and sometimes a photo)', 'Proof of address', 'Bank account details in your name', 'Income / source-of-funds information as required by their compliance process'],
        'Many firms now offer digital onboarding with document upload and a video call. Approval timing varies; a few working days is common, but always follow your broker’s status updates.'],
      ['Step 3 — Fund your account',
        'When the account is active, transfer funds from your bank to the broker’s designated client / funding instructions — not to a personal mobile wallet of an “agent.”',
        'Start with an amount you can afford to leave invested and to see fluctuate. Some shares trade at low per-share prices, but costs and diversification still matter on small accounts.',
        'Keep a note of each deposit date and amount. That makes later reconciliation with your portfolio tracker much easier.'],
      ['Step 4 — Place your first order',
        'Log into the broker app, search by company symbol (for example a liquid large name you have researched), choose buy, quantity, and order type. Limit orders let you set the maximum price you are willing to pay.',
        'PSX has defined trading sessions on business days; exact hours and holidays are published by the exchange. Outside those times you generally cannot get a normal continuous-market fill.',
        'After a fill, download or save the contract note. That document is the source of truth for price, quantity and charges.'],
      ['Step 5 — Research before you size up',
        'A first small trade can be a learning exercise. Scaling up should wait until you understand the business, the risks, and how much of your savings that position represents.',
        'At minimum, read recent financial results, check debt and cash generation, and avoid buying only because a tip circulated in a group chat.',
        'PSX Tracker does not replace research. It helps you record what you bought, what you paid (including fees), and what you later sell — so your personal results stay honest.'],
      ['Taxes and charges to expect',
        'Expect broker commission, exchange/CDC-related charges where applicable, and tax items such as capital gains treatment on sells and withholding on dividends. Rates and rules are set by authorities and can change with each budget cycle.',
        'Treat any percentage you read on a blog as a hint to verify, not as a permanent fact. Your broker statements and FBR updates are safer sources.'],
      ['Common beginner mistakes',
        ['Putting almost all savings into one tip-driven stock', 'Ignoring fees until they quietly shrink returns', 'Panic selling every dip without a plan', 'Never reconciling broker balances with a personal ledger', 'Using borrowed money for speculative trades'],
        'A simple written plan — how much you invest monthly, what you refuse to buy, and how you will review — beats improvising under stress.'],
      ['Keep a portfolio record from day one',
        'Once trades exist, enter them in a portfolio tool (such as PSX Tracker) or a careful spreadsheet. Include buys, sells, dividends and cash movements.',
        'Clean records make FIFO-style cost basis, tax season reviews and “how am I actually doing?” questions possible. Messy records turn every statement into a forensic project.',
        disclaimer],
    ],
    related: ['choosing-a-psx-broker', 'psx-with-limited-capital', 'importing-broker-trades', 'stock-factors-investors-watch'],
  },

  'choosing-a-psx-broker': {
    title: 'Choosing a PSX stock broker',
    blurb: 'A practical checklist for apps, fees, funding and statements.',
    description: 'How to evaluate Pakistan Stock Exchange brokers: licensing, costs, apps, deposits and exportable statements — without relying on outdated fee tables.',
    intro: 'Your broker is the gateway to PSX. The “best” firm is the one that is properly licensed, charges transparently, lets you fund and withdraw safely, and gives you statements you can trust. Fee cards go stale quickly, so treat this as a checklist you verify yourself.',
    sections: [
      ['Start with licensing, not ads',
        'Confirm the broker is authorised to offer PSX trading through official PSX or SECP information, not only a sponsored social post.',
        'Understand how your shares are held (typically via CDC sub-account arrangements your broker sets up) and keep login security under your control — never share OTPs.'],
      ['Costs you should verify on today’s schedule',
        'Ask for or download the current commission structure, CDC or custody-related charges, and any account maintenance or inactivity fees.',
        'Compare total cost for the way you trade (frequent small orders vs occasional larger ones). A headline commission can look cheap until other line items appear on the contract note.',
        'Save a copy of the fee schedule you were shown when you opened the account.'],
      ['App quality and order confidence',
        'You will use the app under time pressure. Check how clear order tickets are, whether you can see open orders and fills, and how contract notes are delivered.',
        'If the app is confusing on day one, it will be worse in a volatile session.'],
      ['Funding, withdrawals and support',
        'Test deposit instructions with a small amount first. Confirm withdrawal timelines and whether support answers before you move a large balance.',
        'Prefer funding from a bank account in your own name and the broker’s published client account details.'],
      ['Statements and portfolio tracking',
        'Good brokers make it easy to download trade history. Clean exports reduce errors when you import into PSX Tracker or reconcile manually.',
        'If exports are painful, budget extra time for bookkeeping — or choose a broker that respects your need for records.',
        disclaimer],
    ],
    related: ['start-investing-on-psx', 'importing-broker-trades', 'psx-with-limited-capital'],
  },

  'psx-with-limited-capital': {
    title: 'Starting on PSX with limited capital',
    blurb: 'Small accounts, real costs, and habits that compound.',
    description: 'How to begin PSX investing with limited capital: costs, concentration risk, patience and clean record-keeping.',
    intro: 'You can start with a modest amount, but small accounts feel fees and mistakes more sharply. The goal is a durable process: affordable trades, sensible sizing, and books you can trust as the account grows.',
    sections: [
      ['What “limited capital” changes',
        'Fixed charges and minimum practical order sizes matter more when the portfolio is small. Two unnecessary trades can erase weeks of careful saving.',
        'Diversification is harder with tiny balances. Holding five micro-positions you cannot follow is worse than two names you understand.'],
      ['Build the funding habit first',
        'Decide a monthly amount you can invest without touching rent, emergency cash or money you will need within a year.',
        'Automating a transfer to your broker (when your bank allows) beats waiting for “perfect” market timing you will never get.'],
      ['Respect costs and odd lots',
        'Before you buy, estimate commission and other charges as a percentage of the order. If costs are huge relative to the trade, wait until you can place a more sensible size — or choose a less expensive route your broker offers.',
        'Always use current broker figures, not memory of an old blog post.'],
      ['Keep the portfolio simple',
        'Write down why you own each name. If you cannot explain it in two sentences, you will not hold it calmly when prices move.',
        'Reinvest dividends only when it fits your plan; sometimes cash is fine while the account is small.'],
      ['Record-keeping is a return skill',
        'Log every buy, sell, fee and dividend. On a small account, a missed fee is a large percentage error.',
        'PSX Tracker is built for that ledger so you can see personal performance instead of guessing from chat screenshots.',
        disclaimer],
    ],
    related: ['start-investing-on-psx', 'choosing-a-psx-broker', 'realistic-psx-returns'],
  },

  'realistic-psx-returns': {
    title: 'Realistic returns on the Pakistan Stock Exchange',
    blurb: 'Dividends, capital gains, risk and why averages are not promises.',
    description: 'A plain-English look at how PSX investors earn — or lose — money through dividends and capital gains, including costs, taxes and risk.',
    intro: 'People ask how much they can make on PSX. There is no honest fixed number. Outcomes depend on what you buy, how long you hold, what you pay in costs and taxes, and how markets behave. This page frames the building blocks without selling a dream.',
    sections: [
      ['Two engines: income and price change',
        'Dividends (and similar distributions) are cash or value you may receive while you hold. Capital gains appear when you sell above your cost; capital losses appear when you sell below.',
        'A stock can pay dividends and still lose money overall if the price falls more than the income you received. Looking at only one number hides that story.'],
      ['Why someone else’s return is not yours',
        'Index charts and influencer screenshots leave out your entry price, fees, taxes and behaviour. They also leave out periods of painful drawdown.',
        'Your measurable return is what your own ledger says after costs.'],
      ['Costs and taxes are part of return',
        'Commission, other trading charges, and tax on gains or dividend withholding reduce what you keep. Rules change; verify with current FBR and broker information.',
        'If you ignore costs, every strategy looks better on paper than in your bank account.'],
      ['Risk is not optional',
        'Equity prices can fall for long stretches. Company-specific news can gap a stock overnight. Concentration in one tip amplifies that risk.',
        'Money needed soon for tuition, medical costs or debt payments is usually a poor match for volatile shares.'],
      ['How to review your own results',
        'Separate unrealized marks on open positions from realized results on closed trades, and track dividend income on its own line.',
        'PSX Tracker surfaces those lenses so you can judge your process with facts — not vibes.',
        disclaimer],
    ],
    related: ['understanding-unrealized-vs-realized', 'tracking-psx-dividends', 'cgt-basics-pakistan-stocks'],
  },

  'is-psx-investing-halal': {
    title: 'Is investing on PSX halal? A plain overview',
    blurb: 'How Muslim investors think about screening — not a fatwa.',
    description: 'Educational overview of Shariah-conscious equity investing on PSX, screening ideas, and why personal scholarly guidance still matters.',
    intro: 'Many Muslim investors want stock-market participation that aligns with their faith. Practices differ by scholar and methodology. This page explains common ideas in plain language. It is not a religious ruling and not personal advice.',
    sections: [
      ['Why people screen equities',
        'Equity ownership means sharing in a company’s business. If that business conflicts with an investor’s religious constraints, they may avoid it or require purification rules their advisor recommends.',
        'Screening frameworks try to encode those concerns into publishable tests and lists.'],
      ['Business activity screens',
        'Methodologies often exclude companies whose primary activities fall into prohibited categories under the screen’s rules. Definitions and thresholds belong to the published standard — not to social-media summaries.'],
      ['Financial ratio screens',
        'Some frameworks also look at balance-sheet or income ratios (for example leverage or non-compliant income mixes). Exact cut-offs vary by index or advisor.',
        'Never invent permanent numbers from memory; read the current rulebook you intend to follow.'],
      ['Lists are tools, not guarantees',
        'A name that passes a screen today can fail after a review. A name that passes is not automatically a good investment — only potentially eligible under that methodology.',
        'Re-check before you buy and periodically while you hold.'],
      ['Your next step',
        'Consult a qualified scholar or advisor for your situation, use official or reputable screening sources, and keep ordinary investment diligence.',
        'PSX Tracker only records the holdings you choose; it does not certify Shariah compliance.',
        disclaimer],
    ],
    related: ['kmi-and-shariah-screening', 'start-investing-on-psx', 'stock-factors-investors-watch'],
  },

  'kmi-and-shariah-screening': {
    title: 'KMI-style Shariah screening on PSX',
    blurb: 'What index-style Islamic screens try to do.',
    description: 'Understand KMI-style Shariah equity screening on PSX: published rules, constituent lists, and how investors use them carefully.',
    intro: 'KMI and similar screens publish methodologies and stock lists so investors can see which companies currently meet a defined Shariah framework. Think of them as rulebooks with updates — not permanent halal stamps.',
    sections: [
      ['Indexes vs personal rulings',
        'An index methodology is one structured approach. Your advisor may add stricter filters or different interpretations.',
        'Always know which list you are following and when it was last reviewed.'],
      ['What typically gets examined',
        'Public methodologies usually discuss business segments and selected financial ratios. The official documentation is the source of truth for definitions and thresholds.',
        'Third-party apps and posts can lag behind reconstitutions — verify against the publisher when stakes are high.'],
      ['Using a compliant universe in practice',
        'Many investors build watchlists from a current universe, then apply normal fundamental analysis: profitability, debt, valuation and governance.',
        'Screening answers “eligible under this method?” — not “will this make money?”'],
      ['Portfolio hygiene still applies',
        'If you invest in screened names, track lots, dividends and sells like any other portfolio. Faith-conscious investing does not remove the need for records or risk management.',
        disclaimer],
    ],
    related: ['is-psx-investing-halal', 'watchlists-and-alerts', 'stock-factors-investors-watch'],
  },

  'stock-factors-investors-watch': {
    title: 'Stock factors PSX investors often watch',
    blurb: 'A research checklist for quality, risk and valuation context.',
    description: 'Common fundamental factors used when researching PSX stocks — business quality, profitability, leverage, cash flow and valuation — explained for beginners.',
    intro: 'Serious investors rarely buy on price charts alone. They gather evidence about the business, the balance sheet and the price they are asked to pay. This checklist is a starting map, not a scoring product and not a buy list.',
    sections: [
      ['Business quality and durability',
        'Ask what the company sells, who pays, and why customers might stay. Read annual reports and result presentations instead of relying on a single tip.',
        'A clear business model is easier to hold through volatility than a story you do not understand.'],
      ['Growth, margins and returns',
        'Look at whether revenue and profits are rising for believable reasons, and whether margins are stable or fragile.',
        'Return measures such as return on equity can help, but only beside leverage and earnings quality — high ROE financed by dangerous debt is not free excellence.'],
      ['Balance sheet and cash flow',
        'Debt service, interest coverage and cash generation show how a company survives slowdowns. Paper profits with weak cash flow deserve extra scepticism.',
        'Sector context matters: banks, manufacturers and funds do not share one “perfect” balance-sheet shape.'],
      ['Valuation needs a peer frame',
        'Multiples such as P/E only mean something next to growth, risk and comparable companies. Cheap can mean bargain or value trap.',
        'Write down your assumptions before you anchor on a single ratio.'],
      ['From research to personal records',
        'After you buy, your outcome depends on your cost, fees, dividends and sell price. Tools like PSX Tracker keep that personal history straight while you continue learning how to analyse businesses.',
        disclaimer],
    ],
    related: ['pe-ratio-for-psx-stocks', 'graham-style-margin-of-safety', 'analyze-cement-stocks-psx', 'analyze-pakistani-banks-psx'],
  },

  'pe-ratio-for-psx-stocks': {
    title: 'P/E ratio for PSX stocks explained',
    blurb: 'What price-to-earnings means — and when it misleads.',
    description: 'Plain-English guide to the price-to-earnings ratio for Pakistani stocks: calculation idea, peer comparison and common pitfalls.',
    intro: 'The price-to-earnings (P/E) ratio compares a company’s share price with its earnings per share. Investors use it as a quick valuation lens. It is useful in context and dangerous in isolation.',
    sections: [
      ['The basic idea',
        'In simple terms, P/E asks how many years of current earnings you are paying for at today’s price. Providers may use trailing earnings (past periods) or forward estimates (forecasts). Know which one you are reading.',
        'If earnings are near zero or negative, classic P/E can become meaningless or misleading — look at why earnings collapsed before trusting the multiple.'],
      ['Compare like with like',
        'A bank, a utility and a cyclical manufacturer can deserve different typical ranges. Prefer peers in the same sector and similar business models.',
        'Also compare the same company across years. A multiple that looks “low” versus history may reflect higher risk, not a gift.'],
      ['Ways P/E fools beginners',
        ['One-off profits that inflate earnings for a single year', 'Accounting changes that move EPS without changing cash reality', 'Cyclical peaks that make earnings look permanently strong', 'Ignoring debt: two firms with similar P/E can have very different risk'],
        'Always open the financial statements behind the ratio.'],
      ['How this fits portfolio tracking',
        'P/E helps at research time. After you own shares, your personal return is about your cost basis and cashflows. Track those in PSX Tracker; do not confuse the market’s multiple with your performance.',
        disclaimer],
    ],
    related: ['stock-factors-investors-watch', 'graham-style-margin-of-safety', 'psx-charts-in-app'],
  },

  'graham-style-margin-of-safety': {
    title: 'Intrinsic value and margin of safety',
    blurb: 'Why careful investors want room for error on price.',
    description: 'A conceptual introduction to intrinsic value and margin of safety for equity investors, including humility about models and estimates.',
    intro: 'Intrinsic value is an estimate of what a business is worth based on its cash flows, assets or earnings power. Margin of safety means buying only when market price sits meaningfully below that careful estimate — so mistakes hurt less.',
    sections: [
      ['Estimates are not oracle prices',
        'Different reasonable investors can produce different values from the same filings. Small changes in growth or discount assumptions move results a lot.',
        'Treat any single “fair value” number — especially from strangers online — as a hypothesis to test, not a fact.'],
      ['What margin of safety is for',
        'If your analysis might be wrong (it might), paying a discounted price leaves room for bad luck, slower growth or accounting surprises.',
        'Thin margins of safety turn investing into a requirement that you are nearly perfect. That is a fragile plan.'],
      ['Practical habits on PSX',
        'Use filings, conservative assumptions, and peer checks. Prefer businesses you understand. Avoid leverage that forces you to sell at the worst time.',
        'Document why the price looked attractive when you bought. Hindsight rewrites memory otherwise.'],
      ['After the purchase',
        'Your wealth change comes from dividends and the difference between sale proceeds and what you paid, including fees. Record those facts carefully.',
        'PSX Tracker focuses on that personal ledger while you keep refining how you estimate value.',
        disclaimer],
    ],
    related: ['pe-ratio-for-psx-stocks', 'stock-factors-investors-watch', 'understanding-unrealized-vs-realized'],
  },

  'analyze-cement-stocks-psx': {
    title: 'How to analyze cement stocks on PSX',
    blurb: 'Volumes, energy costs, leverage and peer valuation.',
    description: 'Educational checklist for researching Pakistani cement companies listed on PSX: dispatches, costs, margins, debt and valuation context.',
    intro: 'Cement producers are cyclical. Demand from construction, energy and fuel costs, industry capacity and pricing power can swing results. A structured checklist keeps research grounded before you compare tickers.',
    sections: [
      ['Volumes and plant utilisation',
        'Track dispatches and how fully plants are used. Rising volumes with weak pricing may not help shareholders; strong pricing with collapsing volumes has its own risks.',
        'Read company notes and industry data rather than a single social-media chart.'],
      ['Cost stack and margins',
        'Energy, fuel and freight often dominate. Gross and operating margins across a cycle tell you more than one lucky quarter.',
        'Ask what happens to the company if energy costs spike or demand slows for a year.'],
      ['Balance sheet and cash',
        'Expansion projects can raise debt. Follow leverage, interest coverage and cash flow, not only accounting profit.',
        'Dividend capacity depends on cash and debt service, not optimism.'],
      ['Valuation inside the peer set',
        'Compare multiples and dividend history among cement names, adjusting for plant efficiency, balance-sheet strength and growth plans.',
        'This remains research education — not a recommendation to buy or sell any company.',
        disclaimer],
    ],
    related: ['stock-factors-investors-watch', 'pe-ratio-for-psx-stocks', 'analyze-pakistani-banks-psx'],
  },

  'analyze-pakistani-banks-psx': {
    title: 'How to analyze Pakistani bank stocks',
    blurb: 'Deposits, NIM, asset quality, capital and valuation.',
    description: 'Educational overview of metrics used when researching PSX-listed banks: deposits, net interest margin, NPLs, capital adequacy and price-to-book thinking.',
    intro: 'Banks are not cement plants. They take deposits, make loans and earn spreads and fees while managing credit risk and capital rules. Use bank-specific lenses before you compare them with industrial companies on a simple P/E.',
    sections: [
      ['Franchise and funding',
        'A durable deposit base — especially lower-cost deposits — supports lending. Watch deposit growth and mix in investor presentations.',
        'Rapid loan growth without funding quality can be a warning, not a trophy.'],
      ['Net interest margin and fees',
        'Net interest margin (NIM) reflects earning assets versus funding costs. Rate cycles move NIM; read management commentary for drivers.',
        'Fee income and operating efficiency also shape profits when margins compress.'],
      ['Asset quality and capital',
        'Non-performing loans, provisioning and capital adequacy show whether earnings are resilient. Credit losses can erase years of apparent progress.',
        'Regulated capital ratios exist for a reason — skimping here is not a free boost to ROE.'],
      ['Returns and valuation',
        'Investors often watch ROE, dividend patterns and price-to-book alongside earnings multiples. Compare peers across cycles rather than one snapshot.',
        'If you invest, record your lots and dividends so personal results stay measurable in a tool like PSX Tracker.',
        disclaimer],
    ],
    related: ['analyze-cement-stocks-psx', 'stock-factors-investors-watch', 'pe-ratio-for-psx-stocks'],
  },
};
