/** Real last-edited dates for public URLs. Sitemap lastmod reads these. Do not stamp the build date. */
export const PAGE_UPDATED = {
  '/': '2026-09-23',
  '/about': '2026-09-17',
  '/privacy': '2026-09-19',
  '/terms': '2026-09-17',
  '/contact': '2026-09-17',
  '/guides': '2026-09-23',
  '/how-to-use': '2026-09-23',
  '/how-it-works': '2026-09-19',
  '/guides/best-psx-portfolio-tracker-excel-alternative': '2026-09-23',
  '/guides/fifo-cost-basis-psx': '2026-09-23',
  '/guides/cgt-basics-pakistan-stocks': '2026-09-23',
  '/guides/mutual-fund-nav-tracking': '2026-09-23',
  '/guides/google-drive-backup-restore': '2026-09-23',
  '/guides/psx-charts-in-app': '2026-09-23',
  '/guides/free-vs-paid-trial': '2026-09-23',
  '/guides/importing-broker-trades': '2026-09-23',
  '/guides/tracking-psx-dividends': '2026-09-23',
  '/guides/multi-portfolio-stocks-vs-funds': '2026-09-23',
  '/guides/watchlists-and-alerts': '2026-09-23',
  '/guides/psx-portfolio-export-reconcile': '2026-09-23',
  '/guides/understanding-unrealized-vs-realized': '2026-09-23',
  '/guides/stock-factors-investors-watch': '2026-09-23',
  '/guides/start-investing-on-psx': '2026-09-23',
  '/guides/realistic-psx-returns': '2026-09-23',
  '/guides/is-psx-investing-halal': '2026-09-23',
  '/guides/psx-with-limited-capital': '2026-09-23',
  '/guides/choosing-a-psx-broker': '2026-09-23',
  '/guides/pe-ratio-for-psx-stocks': '2026-09-23',
  '/guides/kmi-and-shariah-screening': '2026-09-23',
  '/guides/graham-style-margin-of-safety': '2026-09-23',
  '/guides/analyze-cement-stocks-psx': '2026-09-23',
  '/guides/analyze-pakistani-banks-psx': '2026-09-23',
  '/markets': '2026-09-23',
  '/markets/shares/ogdc': '2026-09-23',
  '/markets/shares/ppl': '2026-09-23',
  '/markets/shares/pol': '2026-09-23',
  '/markets/shares/hubc': '2026-09-23',
  '/markets/shares/luck': '2026-09-23',
  '/markets/shares/ffc': '2026-09-23',
  '/markets/shares/mcb': '2026-09-23',
  '/markets/shares/mebl': '2026-09-23',
  '/markets/shares/sys': '2026-09-23',
  '/markets/funds/meezan-islamic-fund': '2026-09-23',
  '/markets/funds/al-meezan-mutual-fund': '2026-09-23',
  '/markets/funds/ubl-stock-advantage-fund': '2026-09-23',
  '/tools': '2026-09-23',
  '/tools/capital-gains': '2026-09-23',
  '/tools/fifo-vs-average': '2026-09-23',
  '/tools/dividend-yield': '2026-09-23',
  '/tools/trade-costs': '2026-09-23',
  '/tools/sip': '2026-09-23',
  '/tools/zakat': '2026-09-23',
};

export const SITEMAP_ORDER = [
  { path: '/', changefreq: 'weekly', priority: '1.0' },
  { path: '/about' },
  { path: '/privacy' },
  { path: '/terms' },
  { path: '/contact' },
  { path: '/guides', priority: '0.8' },
  { path: '/how-to-use', priority: '0.8' },
  { path: '/guides/best-psx-portfolio-tracker-excel-alternative', priority: '0.9' },
  { path: '/guides/fifo-cost-basis-psx' },
  { path: '/guides/cgt-basics-pakistan-stocks' },
  { path: '/guides/mutual-fund-nav-tracking' },
  { path: '/guides/google-drive-backup-restore' },
  { path: '/guides/psx-charts-in-app' },
  { path: '/guides/free-vs-paid-trial' },
  { path: '/guides/importing-broker-trades' },
  { path: '/guides/tracking-psx-dividends' },
  { path: '/guides/multi-portfolio-stocks-vs-funds' },
  { path: '/guides/watchlists-and-alerts' },
  { path: '/guides/psx-portfolio-export-reconcile' },
  { path: '/guides/understanding-unrealized-vs-realized' },
  { path: '/guides/stock-factors-investors-watch' },
  { path: '/guides/start-investing-on-psx' },
  { path: '/guides/realistic-psx-returns' },
  { path: '/guides/is-psx-investing-halal' },
  { path: '/guides/psx-with-limited-capital' },
  { path: '/guides/choosing-a-psx-broker' },
  { path: '/guides/pe-ratio-for-psx-stocks' },
  { path: '/guides/kmi-and-shariah-screening' },
  { path: '/guides/graham-style-margin-of-safety' },
  { path: '/guides/analyze-cement-stocks-psx' },
  { path: '/guides/analyze-pakistani-banks-psx' },
  { path: '/markets', priority: '0.8' },
  { path: '/markets/shares/ogdc' },
  { path: '/markets/shares/ppl' },
  { path: '/markets/shares/pol' },
  { path: '/markets/shares/hubc' },
  { path: '/markets/shares/luck' },
  { path: '/markets/shares/ffc' },
  { path: '/markets/shares/mcb' },
  { path: '/markets/shares/mebl' },
  { path: '/markets/shares/sys' },
  { path: '/markets/funds/meezan-islamic-fund' },
  { path: '/markets/funds/al-meezan-mutual-fund' },
  { path: '/markets/funds/ubl-stock-advantage-fund' },
  { path: '/tools', priority: '0.8' },
  { path: '/tools/capital-gains' },
  { path: '/tools/fifo-vs-average' },
  { path: '/tools/dividend-yield' },
  { path: '/tools/trade-costs' },
  { path: '/tools/sip' },
  { path: '/tools/zakat' },
  { path: '/how-it-works', priority: '0.8' },
];
