import { TRIAL_DAYS } from './product.js';

const disclaimer =
  'This guide is educational and describes how PSX Tracker works. It is not investment, tax or legal advice. Confirm rules and figures with your broker, FBR guidance and professional advisors.';

/**
 * App / workflow guides as full articles.
 * Section shape: [heading, ...blocks] — string paragraphs or string[] bullets.
 * @type {Record<string, import('./learnGuidePages.js').GuidePage extends never ? any : {
 *   title: string, description: string, intro: string, blurb: string,
 *   sections: [string, ...(string|string[])[]][], related?: string[]
 * }>}
 */
export const trackerGuidePages = {
  'fifo-cost-basis-psx': {
    title: 'FIFO cost basis on the Pakistan Stock Exchange',
    blurb: 'How first-in, first-out matching shapes average cost and realized gains.',
    description: 'A full plain-English guide to FIFO lot matching for PSX share sales, day trades, fees in cost basis, and how PSX Tracker applies it.',
    intro: 'When you sell shares, which purchase lots did you close? First-in, first-out (FIFO) answers that by matching sells to your oldest remaining buys first. That choice changes average cost, unrealized marks and realized profit — even when the sale price is identical. This article explains FIFO in practice and how PSX Tracker models it.',
    sections: [
      ['What FIFO means in a portfolio',
        'Imagine you bought the same symbol three times at different prices, then sold part of the position. FIFO closes the earliest open lots before newer ones. Your broker may document matching rules differently for tax forms; this guide describes the lot logic investors and trackers commonly use to reconstruct a book.',
        'Without a rule, “average cost” becomes a blur. With FIFO, each sale has a clear trail back to specific buys, which makes later audits and exports easier to defend to yourself.'],
      ['Why matching changes your numbers',
        'Unrealized gain compares market value with the cost of lots you still hold. Realized gain compares sale proceeds with the cost of lots you closed, including related charges when you record them.',
        'Selling into older low-cost lots can realize more taxable-looking gain than selling newer high-cost lots at the same market price. That is not a tip to trade for tax optics — it is a reminder that lot order is part of the math.',
        'If your ledger mixes fees incorrectly or duplicates buys, FIFO will faithfully produce wrong answers. Garbage lots in, garbage P&L out.'],
      ['Same-day buys and sells',
        'Intraday churn can distort long-term average cost if every minute trade stays in the lot stack. Many investors conceptually square same-day activity before it permanently reshapes basis.',
        'PSX Tracker includes day-trade squaring behaviour so short-term round trips are less likely to quietly ruin the cost of shares you meant to keep. Still review busy days after imports.'],
      ['Fees belong in what you paid',
        'Commission, sales tax, CDC and similar charges are part of economic cost. Leaving them out makes break-even look better than reality.',
        'Enter fees on the trade (or as your import mapping provides) so FIFO cost per share reflects what left your pocket.'],
      ['How PSX Tracker helps',
        'You record buys, sells and fees once. The app applies FIFO-style matching, shows open holdings and realized trades, and lets you export for reconciliation against broker contract notes.',
        'After a large import, skim holdings quantities and a few realized lines before you trust year-end totals.',
        disclaimer],
    ],
    related: ['cgt-basics-pakistan-stocks', 'understanding-unrealized-vs-realized', 'importing-broker-trades'],
  },

  'cgt-basics-pakistan-stocks': {
    title: 'Capital gains tax basics for Pakistani stocks',
    blurb: 'High-level CGT ideas investors track alongside realized gains.',
    description: 'Plain-language overview of capital gains concepts for PSX share sales, holding periods, records and what a portfolio tracker can (and cannot) do.',
    intro: 'Capital gains tax (CGT) on listed shares is about taxable profit when you dispose of holdings — not about how much cash you withdrew from a broker. Rules and rates change with budgets and ordinances. This article explains the ideas investors usually track so conversations with a tax professional start from cleaner facts.',
    sections: [
      ['Gain versus cash in your pocket',
        'A simplified picture of realized gain is sale proceeds minus the cost of the lots you sold (and related selling costs you include). That figure is not the same as “I transferred money to my bank.”',
        'Deposits, withdrawals and dividends follow different stories. Mixing them with capital gains is a common source of confusion at year end.'],
      ['Holding periods and changing rates',
        'Pakistan has used different treatments depending on how long shares were held and which rules applied for that tax year. Do not memorize a percentage from an old blog post.',
        'Check current FBR guidance and your advisor for the year you are filing. PSX Tracker fields that look CGT-oriented are informational aids, not a filed computation.'],
      ['Why lot matching shows up in tax season',
        'Which buys a sale closes changes the gain. If your records cannot reconstruct lots, you will struggle to explain numbers on statements.',
        'FIFO-style books and saved contract notes make that reconstruction possible. Fix import duplicates early — before December urgency.'],
      ['What a tracker can and cannot do',
        'PSX Tracker can show realized P&L with fees and help you review sells. It does not submit returns, apply every exemption automatically, or replace a qualified tax advisor.',
        'Export your ledger, keep broker PDFs, and reconcile large disposals before you sign anything.'],
      ['Good habits year-round',
        ['Save contract notes when trades fill', 'Record dividends and withholding separately from share sells', 'Export after messy imports and spot-check quantities', 'Ask a professional when rules look unclear — do not guess from WhatsApp'],
        disclaimer],
    ],
    related: ['fifo-cost-basis-psx', 'understanding-unrealized-vs-realized', 'tracking-psx-dividends'],
  },

  'mutual-fund-nav-tracking': {
    title: 'Tracking mutual fund NAV and daily P&L',
    blurb: 'Units, NAV sync and day-over-day fund performance in one place.',
    description: 'Full guide to tracking open-end mutual funds in PSX Tracker: separate portfolios, units and cost, NAV sync and daily P&L caveats.',
    intro: 'Open-end mutual funds do not trade like PSX board lots, but you still need units, purchase cost and a current net asset value (NAV). This article walks through how PSX Tracker keeps fund books usable day to day.',
    sections: [
      ['Why funds get their own portfolio',
        'Share lots use exchange prices and FIFO share quantities. Funds use units × NAV. Mixing both in one ledger blurs average cost and daily moves.',
        'Create or switch to a mutual fund portfolio so each book stays coherent while sharing the same login.'],
      ['Recording units and cost',
        'Log purchases, redemptions and transfers in units. Average cost and market value follow from those units and the NAV you apply.',
        'Reinvested dividends that buy more units should be reflected so income and unit count stay aligned with the fund statement.'],
      ['NAV sync and stale data',
        'When sync is available, PSX Tracker can refresh NAVs from its catalog path so valuations move with published figures.',
        'If a fund looks stuck, refresh, confirm the fund exists in the catalog, and compare against the AMC or statement before reacting to a “flat” day.'],
      ['Reading daily P&L on funds',
        'Day change typically compares the latest NAV mark with the prior mark on your units. Gaps in data produce gaps in P&L — treat missing NAVs as a data problem, not a trading signal.',
        'For longer performance, combine NAV moves with your actual cash invested and redeemed, not only one green daily number.',
        disclaimer],
    ],
    related: ['multi-portfolio-stocks-vs-funds', 'tracking-psx-dividends', 'free-vs-paid-trial'],
  },

  'google-drive-backup-restore': {
    title: 'Google Drive backup and restore',
    blurb: 'Keep portfolio snapshots in your Drive and recover when sync fails.',
    description: 'How PSX Tracker syncs to Google Drive: what is saved, pending changes, Retry vs Restore, and downloading unsynced JSON safely.',
    intro: 'Google Drive sync lets a portfolio follow you across devices using files your Google account owns. Failures happen — networks drop, tokens expire, two devices edit at once. Knowing Retry, Restore and download options turns a scary banner into a controlled recovery.',
    sections: [
      ['What Drive sync actually stores',
        'Successful sync writes portfolio snapshot and settings-style data into Drive-managed files for this app. A Sheets export, when you use it, is a derived transaction view — useful, but not a substitute for understanding snapshot sync.',
        'Your Google account remains the owner of those files. Disconnecting or revoking access has consequences; read the in-app and Privacy explanations before you change permissions.'],
      ['Pending local changes',
        'If an upload fails, PSX Tracker can keep a pending local copy so your latest edits are not silently discarded. The sidebar sync footer surfaces status, a short error, and actions.',
        'Do not keep trading on two devices with conflicting pending states without deciding which book should win.'],
      ['Retry versus Restore',
        'Retry attempts to push the pending local snapshot again — the usual first move after a temporary network error.',
        'Restore is stronger medicine: it preserves a recovery copy of unsynced work, then reloads the cloud version. Confirm before you restore if you might overwrite newer local trades.',
        'When in doubt, download pending JSON first so you have a file offline.'],
      ['Download / keep pending',
        'Use download or keep-pending style actions to save unsynced data before you accept cloud state. That file is your seatbelt.',
        'After a clean sync, open the other device and confirm it shows the same holdings before you enter new trades there.',
        disclaimer],
    ],
    related: ['free-vs-paid-trial', 'importing-broker-trades', 'psx-portfolio-export-reconcile'],
  },

  'psx-charts-in-app': {
    title: 'Using PSX charts in the app',
    blurb: 'Candlesticks, indicators and portfolio context on research charts.',
    description: 'How to use PSX Tracker charts for research: opening tickers, indicators, portfolio context on the chart, and data-delay caveats.',
    intro: 'Charts in PSX Tracker are for research and context. They do not send orders to your broker. Used well, they help you see structure and your own position history side by side — without confusing a drawing tool for a crystal ball.',
    sections: [
      ['Open a chart the useful way',
        'From Charts explorer or a stock profile, pick a symbol and timeframe. Candlesticks and volume are a compact language for price history; they do not know your risk tolerance.',
        'Start with liquid names while you learn the controls so gaps and thin prints confuse you less.'],
      ['Indicators and drawings',
        'Moving averages, RSI, Bollinger bands and drawing tools may be available depending on plan limits. They frame history; they do not guarantee future returns.',
        'If an indicator conflicts with the financial story of the company, believe the need for more research — not the need for more indicators.'],
      ['Portfolio context on the chart',
        'When you hold a name, the app can surface open or realized context so research stays tied to lots you actually own.',
        'Always sanity-check marks against broker or exchange figures if something looks off.'],
      ['Delays, gaps and refresh',
        'Quotes and bars can be delayed or incomplete. Refresh when a chart looks stale, and treat missing sessions as data issues rather than mysterious signals.',
        'Charts complement — they do not replace — filings, position sizing and a written plan.',
        disclaimer],
    ],
    related: ['watchlists-and-alerts', 'fifo-cost-basis-psx', 'free-vs-paid-trial'],
  },

  'free-vs-paid-trial': {
    title: `Free vs Paid after your ${TRIAL_DAYS}-day trial`,
    blurb: 'What the trial unlocks and how Free and Paid differ.',
    description: `Full explanation of the ${TRIAL_DAYS}-day trial, Free plan limits, Paid access, and how Google Drive relates to plan tiers in PSX Tracker.`,
    intro: `New approved accounts typically receive a ${TRIAL_DAYS}-day full trial so you can explore the product before choosing Free limits or Paid access. This article spells out what that means in practice — including what Drive sync is and is not.`,
    sections: [
      ['During the trial',
        `While the trial is active you can explore the full toolset under the product’s trial rules. Starting does not require entering a card in-app for the trial itself.`,
        'Access may still require owner approval before the trial clock meaningfully starts. If you are stuck on a pending screen, use the status messaging and contact paths on the site.'],
      ['Free after the trial',
        'When the trial ends, Free access can continue inside published limits — for example caps on alerts, scans or other tools described on the homepage and plan materials.',
        'Free is meant to remain useful for core tracking; it is not a promise of every premium research feature forever.'],
      ['Paid access',
        'Paid removes key limits so heavier use stays comfortable. Activation follows the payment confirmation process described on the site (working with support through listed methods).',
        'Keep receipts and the email on your account consistent so upgrades apply to the right login.'],
      ['Google Drive is a permission, not a “plan file”',
        'Drive sync is something you grant so backups live in your Google account. Plan tier affects product features; Drive files remain yours under Google’s controls.',
        'You can often use portfolio features without Drive, but multi-device backup is weaker. Disconnect carefully if you are unsure.',
        disclaimer],
    ],
    related: ['google-drive-backup-restore', 'psx-charts-in-app', 'watchlists-and-alerts'],
  },

  'importing-broker-trades': {
    title: 'Importing broker trades into PSX Tracker',
    blurb: 'CSV, Excel, screenshots and optional Gmail attachments.',
    description: 'Complete guide to importing PSX trades into PSX Tracker via manual entry, spreadsheets, OCR screenshots and optional Gmail attachment import — with review steps.',
    intro: 'Clean imports protect FIFO lots and year-end sanity. Prefer structured files when you can, and treat every AI or OCR suggestion as a draft until you approve it. This article covers the main paths inside PSX Tracker.',
    sections: [
      ['Manual entry and spreadsheets',
        'You can add trades by hand or upload CSV/Excel mapped to buys, sells, dividends and cash events. Normalize ticker symbols and dates before you confirm.',
        'If your broker export uses odd column names, map carefully once and reuse the habit. A wrong sign on quantity is worse than typing three trades manually.'],
      ['Screenshots and OCR',
        'Optional OCR can read a statement image when a file export is painful. Optical character recognition misreads digits and skips rows — especially on blurry photos.',
        'Compare every line to the image before saving. If confidence is low, fall back to CSV or manual entry.'],
      ['Gmail attachments (optional)',
        'Gmail read access is requested only when you choose that import path. You search, pick an attachment, and review the parse before anything hits the ledger.',
        'The app is not asking for permission to send mail as you. Revoke Google access anytime in your Google account settings if you leave that workflow.'],
      ['After every import',
        ['Scan for duplicate trades', 'Confirm broker names and symbols', 'Check holdings against the broker app', 'Export or sync a backup once the book looks right'],
        'Rushing confirmation is how FIFO nightmares begin.',
        disclaimer],
    ],
    related: ['fifo-cost-basis-psx', 'psx-portfolio-export-reconcile', 'google-drive-backup-restore'],
  },

  'tracking-psx-dividends': {
    title: 'Tracking PSX dividends and cash income',
    blurb: 'Record dividends, tax withheld and how income shows in totals.',
    description: 'Full guide to logging PSX share and fund dividends in PSX Tracker: cash vs reinvested payouts, withholding and where income appears in totals.',
    intro: 'Dividends are income related to ownership — not the same event as selling shares. Recording them cleanly keeps Total Return, cash and tax-season stories honest. Here is how to think about dividend events inside PSX Tracker.',
    sections: [
      ['What to record on a dividend',
        'Capture the date that matches your broker or company notice, the ticker, and the amount. If withholding appears on the statement, record it so net income stays explainable.',
        'Use the share or fund book that actually held the position on the relevant date.'],
      ['Cash versus reinvested',
        'Cash dividends increase cash available in the account story. Reinvested dividends purchase more shares or fund units — income still happened, but cash may not sit idle.',
        'If you only record cash and forget reinvested units, holdings drift away from the statement.'],
      ['Withholding and informational totals',
        'Brokers may deduct tax at source on dividends. Tracking that withholding helps you reconcile net credits and informational tax views later.',
        'Your formal tax treatment still follows FBR rules and advisor guidance — the tracker is a ledger aid.'],
      ['Where totals show up',
        'Portfolio summaries typically separate dividend income from unrealized marks and realized trading gains. After dividend season, skim history and summary cards for surprises.',
        'If a payout is missing, check whether you held the name through the required date and whether the event was imported or entered.',
        disclaimer],
    ],
    related: ['understanding-unrealized-vs-realized', 'cgt-basics-pakistan-stocks', 'mutual-fund-nav-tracking'],
  },

  'multi-portfolio-stocks-vs-funds': {
    title: 'Stock vs mutual fund portfolios',
    blurb: 'Keep share and fund books separate without losing one login.',
    description: 'Why PSX Tracker uses separate stock and mutual fund portfolios, how to switch, and how Drive sync relates to multiple books.',
    intro: 'Shares and open-end funds speak different measurement languages. Separate portfolios keep NAV tracking and FIFO share lots from colliding — while one account login still owns both books.',
    sections: [
      ['Why separate books',
        'Equity portfolios care about share quantities, exchange marks and FIFO lots. Fund portfolios care about units and NAVs. Forcing both into one mash-up makes average cost and daily P&L harder to trust.',
        'Separation is bookkeeping hygiene, not a marketing upsell.'],
      ['Create and switch',
        'Use the portfolio switcher to open a stock book or a mutual fund book. Each keeps its own holdings and history.',
        'Name them clearly — for example “PSX shares” and “Open-end funds” — so imports land in the right place.'],
      ['Sync and multi-device caution',
        'Drive backup can cover the portfolios you use. After switching phones, confirm the portfolio name before editing.',
        'Pending sync on portfolio A does not mean portfolio B is safe to overwrite casually. Finish one book’s sync story before juggling devices.'],
      ['Practical workflow',
        'Import broker equity trades into the stock portfolio. Enter fund statement lines into the fund portfolio. Review each on its own schedule.',
        'When you reconcile, match each book to the right broker or AMC statement.',
        disclaimer],
    ],
    related: ['mutual-fund-nav-tracking', 'google-drive-backup-restore', 'importing-broker-trades'],
  },

  'watchlists-and-alerts': {
    title: 'Watchlists and price alerts',
    blurb: 'Follow tickers you do not hold and get notified on moves.',
    description: 'How watchlists and price alerts work in PSX Tracker: building lists, opening charts, setting alerts, and plan or data limits.',
    intro: 'A watchlist holds research candidates without pretending you own them. Alerts nudge you when price crosses a level you chose. Neither places broker orders — they support attention, not autopilot trading.',
    sections: [
      ['Build a watchlist with intent',
        'Add symbols from search or a profile page. Keep the list short enough that you will actually review it.',
        'Watchlist quotes can refresh with market data even when you have no position — useful for patience before buying.'],
      ['Jump into charts and profiles',
        'Open a chart or profile from a watched name to inspect structure and filings-linked context before you size a trade.',
        'If you buy later, the watchlist item does not replace entering the trade in your portfolio book.'],
      ['Setting alerts',
        'Create a price alert for a level that matters to your plan — not every tick. Delivery depends on notification setup and plan limits.',
        'Alerts can fail when devices sleep, browsers block notifications, or data is delayed. They are helpers, not guaranteed fills.'],
      ['Limits and healthy expectations',
        'Free and Paid plans may cap how many alerts you keep. Quotes may be delayed.',
        'Use alerts to remember homework, not to outsource judgment.',
        disclaimer],
    ],
    related: ['psx-charts-in-app', 'free-vs-paid-trial', 'stock-factors-investors-watch'],
  },

  'psx-portfolio-export-reconcile': {
    title: 'Export and reconcile your PSX portfolio',
    blurb: 'Download records and check them against your broker.',
    description: 'How to export PSX Tracker data and reconcile holdings, cash and dividends with broker statements after imports or corporate actions.',
    intro: 'A tracker earns trust only when it matches reality. Export on a schedule and reconcile after big imports, rights issues or messy OCR days. This article is a practical checklist.',
    sections: [
      ['What to export and keep',
        'Use in-app export or Sheets-related flows when available so you have a dated copy outside the browser. Store it where you can find last month’s file.',
        'Exports complement Drive sync; they are snapshots you can email to an advisor or diff locally.'],
      ['Reconcile holdings',
        'Compare quantity and average cost per ticker with the broker app. Investigate mismatches before the next sell so FIFO lots stay clean.',
        'Common culprits: duplicate imports, wrong symbols, forgotten corporate actions, or trades entered in the wrong portfolio.'],
      ['Reconcile cash and income',
        'Check deposits, withdrawals and dividends against bank or broker cash reports for overlapping dates.',
        'If withholding appears on dividends, ensure your ledger’s net and tax lines can explain the credit you saw.'],
      ['After you fix the book',
        'Correct trades, export again, and sync Drive so every device shares the cleaned state. Then place new trades.',
        'Reconciliation is boring — and cheaper than rebuilding a year of lots in April.',
        disclaimer],
    ],
    related: ['importing-broker-trades', 'google-drive-backup-restore', 'tracking-psx-dividends'],
  },

  'understanding-unrealized-vs-realized': {
    title: 'Unrealized vs realized P&L explained',
    blurb: 'Paper gains on open lots versus locked-in results after sells.',
    description: 'Full explanation of unrealized versus realized profit and loss for PSX portfolios, and how PSX Tracker shows both lenses.',
    intro: 'Unrealized P&L moves with the market on shares you still hold. Realized P&L locks in when you sell. Confusing the two leads to celebrating paper gains that never become cash — or ignoring locked-in losses hiding under a green today number.',
    sections: [
      ['Unrealized (open positions)',
        'Roughly: market value minus the cost of lots you still hold. It changes whenever prices move and is not cash until you dispose of the position.',
        'A large unrealized gain can vanish in a bad week. Treat it as mark-to-market information, not a bonus already paid.'],
      ['Realized (closed trades)',
        'Realized results come from sells after cost basis and fees for the lots you closed. They remain in history even if you later repurchase the name.',
        'Realized loss is still a result — ignoring it because you “still believe in the stock” does not erase the closed trade.'],
      ['Income sits beside both',
        'Dividends are not unrealized share gain and not the same as a sell. Track income separately so Total Return has all three stories: open marks, closed trades and distributions.'],
      ['How PSX Tracker helps',
        'Holdings views emphasize open lots; realized views emphasize closed trades. Use both when you review performance.',
        'If the two lenses disagree with your memory, trust the ledger — then fix missing trades until memory and ledger converge.',
        disclaimer],
    ],
    related: ['fifo-cost-basis-psx', 'cgt-basics-pakistan-stocks', 'tracking-psx-dividends', 'realistic-psx-returns'],
  },
};
