import React, { useState } from 'react';
import { changeAccountPassword, requestPasswordReset, requestPasswordSetup, disconnectRememberedDrive } from '../services/auth';
import { SiteFooter } from './SiteFooter';
import { downloadRecoveryCopies } from '../utils/recoveryStorage';
export function ProfilePage({email,name,googleConnected,onDriveDisconnected}:{email:string;name?:string;googleConnected:boolean;onDriveDisconnected?:()=>void}) {
  const [current,setCurrent]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const run=async(action:()=>Promise<void>,success:string)=>{setBusy(true);setMessage('');try{await action();setMessage(success);setCurrent('');setPassword('');setConfirm('');}catch(e){setMessage(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}};
  const input='block w-full mt-2 rounded-xl border border-slate-300 dark:border-slate-700 p-3 bg-white dark:bg-slate-900 text-base';
  return <section className="max-w-2xl mx-auto p-4 sm:p-6"><h1 className="text-3xl font-bold mb-6">Profile & security</h1><div className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-5 mb-6"><p className="font-bold">{name || 'Your account'}</p><p className="break-all text-slate-600 dark:text-slate-300 mt-1">{email}</p><p className="text-sm text-slate-500 dark:text-slate-400 mt-3">{googleConnected?'Google Drive is connected for portfolio sync.':'Email login gives account access. Connect Google Drive from the app to sync your portfolio across devices.'}</p><p className="text-sm text-slate-500 dark:text-slate-400 mt-2">Your PSX Tracker password is separate from your Google password.</p></div>
    <div className="rounded-2xl border border-slate-200 dark:border-slate-800 p-5 mb-6"><h2 className="text-xl font-bold">Remembered Drive access</h2><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">Once linked, your password can open the same Drive portfolio on any device. Your files stay in Google Drive. Signing out keeps this connection; disconnecting removes the saved permission.</p><button type="button" disabled={busy} className="mt-3 min-h-[44px] underline text-sm text-red-600 dark:text-red-400 disabled:opacity-50" onClick={()=>{if(window.confirm('Disconnect remembered Drive access? Your Drive files will stay intact. You will need Google approval again before syncing.'))void run(async()=>{await disconnectRememberedDrive();onDriveDisconnected?.();},'Drive disconnected. Your portfolio files remain in Google Drive.');}}>Disconnect remembered Drive access</button></div>
    <form className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-5 space-y-5" onSubmit={e=>{e.preventDefault();if(password!==confirm){setMessage('New passwords must match.');return;}void run(()=>changeAccountPassword(email,current,password),'Password changed. Use the new password the next time you log in by email.');}}>
      <h2 className="text-xl font-bold">Change password</h2><input type="text" autoComplete="username" value={email} readOnly hidden />
      <label className="block font-medium">Current PSX Tracker password<input className={input} type="password" autoComplete="current-password" required value={current} onChange={e=>setCurrent(e.target.value)} /></label>
      <label className="block font-medium">New password<input className={input} type="password" autoComplete="new-password" required minLength={10} maxLength={72} value={password} onChange={e=>setPassword(e.target.value)} /><span className="block text-sm font-normal text-slate-500 mt-1">Use at least 10 characters.</span></label>
      <label className="block font-medium">Confirm new password<input className={input} type="password" autoComplete="new-password" required minLength={10} maxLength={72} value={confirm} onChange={e=>setConfirm(e.target.value)} /></label>
      <button disabled={busy} className="bg-emerald-600 text-white rounded-xl px-5 py-3 font-bold disabled:opacity-60">{busy?'Please wait…':'Change password'}</button>
      <div className="border-t border-slate-200 dark:border-slate-700 pt-4"><p className="text-sm text-slate-600 dark:text-slate-400">Signed in with Google and haven’t added a password?</p><button disabled={busy} type="button" className="underline py-3 text-emerald-700 dark:text-emerald-400" onClick={()=>void run(()=>requestPasswordSetup(email),'Check your email for a secure link to set up a password. Your Google sign-in will still work.')}>Email me a password setup link</button><br/><button disabled={busy} type="button" className="underline py-2" onClick={()=>void run(()=>requestPasswordReset(email),'If this email has a password account, a reset link is on its way. Check your inbox and spam folder.')}>Forgot your password?</button></div>
      {message&&<p role="status" className="text-sm rounded-xl p-3 bg-slate-100 dark:bg-slate-800">{message}</p>}
    </form><div className="mt-6 rounded-2xl border border-slate-200 dark:border-slate-800 p-5"><h2 className="text-xl font-bold">Local recovery copies</h2><p className="mt-2 text-sm text-slate-600 dark:text-slate-400">Load latest keeps a copy of this device’s previous data before opening your Drive backup. Download those copies here if you need to recover an earlier edit.</p><button type="button" disabled={busy} className="min-h-[44px] mt-3 underline disabled:opacity-50" onClick={()=>void run(()=>downloadRecoveryCopies(email),'Recovery download started. Check your browser downloads.')}>Download recovery copies</button><p className="mt-2 text-xs text-slate-500">Copies stay on this device and can be removed by clearing this site’s browser data.</p></div><div className="mt-8"><SiteFooter /></div></section>;
}
